package mobile

import (
	"encoding/json"
	"errors"

	"github.com/textileio/textile-go/core"
	"github.com/textileio/textile-go/repo"
)

// AddContact calls core AddContact
func (m *Mobile) AddContact(contact string) error {
	var model *repo.Contact
	if err := json.Unmarshal([]byte(contact), &model); err != nil {
		return err
	}

	return m.node.AddContact(model)
}

// Contact calls core Contact
func (m *Mobile) Contact(id string) (string, error) {
	if !m.node.Started() {
		return "", core.ErrStopped
	}

	contact := m.node.Contact(id)
	if contact != nil {
		return toJSON(contact)
	}
	return "", errors.New("contact not found")
}

// Contacts calls core Contacts
func (m *Mobile) Contacts() (string, error) {
	if !m.node.Started() {
		return "", core.ErrStopped
	}

	contacts, err := m.node.Contacts()
	if err != nil {
		return "", err
	}
	if len(contacts) == 0 {
		contacts = make([]core.ContactInfo, 0)
	}
	return toJSON(contacts)
}

// RemoveContact calls core RemoveContact
func (m *Mobile) RemoveContact(id string) error {
	return m.node.RemoveContact(id)
}

// ContactThreads calls core ContactThreads
func (m *Mobile) ContactThreads(id string) (string, error) {
	if !m.node.Started() {
		return "", core.ErrStopped
	}

	infos, err := m.node.ContactThreads(id)
	if err != nil {
		return "", err
	}
	if len(infos) == 0 {
		infos = make([]core.ThreadInfo, 0)
	}
	return toJSON(infos)
}

// ContactQueryEvent represents events generated by a contact query
type ContactQueryEvent struct {
	Type ContactQueryEventType    `json:"type"`
	Data *core.ContactQueryResult `json:"data"`
}

// ContactQueryEventType is used to indicate a type of contact query event
type ContactQueryEventType string

const (
	// ContactQueryData a match was found
	ContactQueryData ContactQueryEventType = "data"
	// ContactQueryDone query is complete or was canceled
	ContactQueryDone = "done"
)

// FindContacts calls core FindContacts
func (m *Mobile) FindContacts(query *core.ContactQuery, cb StringCallback) (func(), error) {
	resCh, errCh, cancel := m.node.FindContacts(query)
	doneFn := func() {
		cb.Call(toJSON(ContactQueryEvent{
			Type: ContactQueryDone,
		}))
	}
	cancelFn := func() {
		cancel.Close()
		doneFn()
	}

	go func() {
		select {
		case err := <-errCh:
			cb.Call("", err)
			return

		case res, ok := <-resCh:
			if !ok {
				doneFn()
				return
			}
			cb.Call(toJSON(ContactQueryEvent{
				Type: ContactQueryData,
				Data: res,
			}))
		}
	}()

	return cancelFn, nil
}
