// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import any "github.com/golang/protobuf/ptypes/any"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Message_Type int32

const (
	Message_PING              Message_Type = 0
	Message_CHAT              Message_Type = 1
	Message_FOLLOW            Message_Type = 2
	Message_UNFOLLOW          Message_Type = 3
	Message_OFFLINE_ACK       Message_Type = 4
	Message_OFFLINE_RELAY     Message_Type = 5
	Message_MODERATOR_ADD     Message_Type = 6
	Message_MODERATOR_REMOVE  Message_Type = 7
	Message_STORE             Message_Type = 8
	Message_BLOCK             Message_Type = 9
	Message_THREAD_INVITE     Message_Type = 100
	Message_THREAD_DATA       Message_Type = 101
	Message_THREAD_ANNOTATION Message_Type = 102
	Message_ERROR             Message_Type = 500
)

var Message_Type_name = map[int32]string{
	0:   "PING",
	1:   "CHAT",
	2:   "FOLLOW",
	3:   "UNFOLLOW",
	4:   "OFFLINE_ACK",
	5:   "OFFLINE_RELAY",
	6:   "MODERATOR_ADD",
	7:   "MODERATOR_REMOVE",
	8:   "STORE",
	9:   "BLOCK",
	100: "THREAD_INVITE",
	101: "THREAD_DATA",
	102: "THREAD_ANNOTATION",
	500: "ERROR",
}
var Message_Type_value = map[string]int32{
	"PING":              0,
	"CHAT":              1,
	"FOLLOW":            2,
	"UNFOLLOW":          3,
	"OFFLINE_ACK":       4,
	"OFFLINE_RELAY":     5,
	"MODERATOR_ADD":     6,
	"MODERATOR_REMOVE":  7,
	"STORE":             8,
	"BLOCK":             9,
	"THREAD_INVITE":     100,
	"THREAD_DATA":       101,
	"THREAD_ANNOTATION": 102,
	"ERROR":             500,
}

func (x Message_Type) String() string {
	return proto.EnumName(Message_Type_name, int32(x))
}
func (Message_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_message_f057e04541b64095, []int{0, 0}
}

type Chat_Flag int32

const (
	Chat_MESSAGE Chat_Flag = 0
	Chat_TYPING  Chat_Flag = 1
	Chat_READ    Chat_Flag = 2
)

var Chat_Flag_name = map[int32]string{
	0: "MESSAGE",
	1: "TYPING",
	2: "READ",
}
var Chat_Flag_value = map[string]int32{
	"MESSAGE": 0,
	"TYPING":  1,
	"READ":    2,
}

func (x Chat_Flag) String() string {
	return proto.EnumName(Chat_Flag_name, int32(x))
}
func (Chat_Flag) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_message_f057e04541b64095, []int{2, 0}
}

type Message struct {
	Type                 Message_Type `protobuf:"varint,1,opt,name=type,proto3,enum=Message_Type" json:"type,omitempty"`
	Payload              *any.Any     `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	RequestId            int32        `protobuf:"varint,3,opt,name=requestId,proto3" json:"requestId,omitempty"`
	IsResponse           bool         `protobuf:"varint,4,opt,name=isResponse,proto3" json:"isResponse,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_f057e04541b64095, []int{0}
}
func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (dst *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(dst, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetType() Message_Type {
	if m != nil {
		return m.Type
	}
	return Message_PING
}

func (m *Message) GetPayload() *any.Any {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *Message) GetRequestId() int32 {
	if m != nil {
		return m.RequestId
	}
	return 0
}

func (m *Message) GetIsResponse() bool {
	if m != nil {
		return m.IsResponse
	}
	return false
}

type Envelope struct {
	Message              *Message `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Pubkey               []byte   `protobuf:"bytes,2,opt,name=pubkey,proto3" json:"pubkey,omitempty"`
	Signature            []byte   `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Envelope) Reset()         { *m = Envelope{} }
func (m *Envelope) String() string { return proto.CompactTextString(m) }
func (*Envelope) ProtoMessage()    {}
func (*Envelope) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_f057e04541b64095, []int{1}
}
func (m *Envelope) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Envelope.Unmarshal(m, b)
}
func (m *Envelope) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Envelope.Marshal(b, m, deterministic)
}
func (dst *Envelope) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Envelope.Merge(dst, src)
}
func (m *Envelope) XXX_Size() int {
	return xxx_messageInfo_Envelope.Size(m)
}
func (m *Envelope) XXX_DiscardUnknown() {
	xxx_messageInfo_Envelope.DiscardUnknown(m)
}

var xxx_messageInfo_Envelope proto.InternalMessageInfo

func (m *Envelope) GetMessage() *Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *Envelope) GetPubkey() []byte {
	if m != nil {
		return m.Pubkey
	}
	return nil
}

func (m *Envelope) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type Chat struct {
	MessageId            string               `protobuf:"bytes,1,opt,name=messageId,proto3" json:"messageId,omitempty"`
	Subject              string               `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	Message              string               `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Flag                 Chat_Flag            `protobuf:"varint,5,opt,name=flag,proto3,enum=Chat_Flag" json:"flag,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Chat) Reset()         { *m = Chat{} }
func (m *Chat) String() string { return proto.CompactTextString(m) }
func (*Chat) ProtoMessage()    {}
func (*Chat) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_f057e04541b64095, []int{2}
}
func (m *Chat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Chat.Unmarshal(m, b)
}
func (m *Chat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Chat.Marshal(b, m, deterministic)
}
func (dst *Chat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Chat.Merge(dst, src)
}
func (m *Chat) XXX_Size() int {
	return xxx_messageInfo_Chat.Size(m)
}
func (m *Chat) XXX_DiscardUnknown() {
	xxx_messageInfo_Chat.DiscardUnknown(m)
}

var xxx_messageInfo_Chat proto.InternalMessageInfo

func (m *Chat) GetMessageId() string {
	if m != nil {
		return m.MessageId
	}
	return ""
}

func (m *Chat) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *Chat) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Chat) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *Chat) GetFlag() Chat_Flag {
	if m != nil {
		return m.Flag
	}
	return Chat_MESSAGE
}

type SignedData struct {
	SenderPubkey         []byte   `protobuf:"bytes,1,opt,name=senderPubkey,proto3" json:"senderPubkey,omitempty"`
	SerializedData       []byte   `protobuf:"bytes,2,opt,name=serializedData,proto3" json:"serializedData,omitempty"`
	Signature            []byte   `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignedData) Reset()         { *m = SignedData{} }
func (m *SignedData) String() string { return proto.CompactTextString(m) }
func (*SignedData) ProtoMessage()    {}
func (*SignedData) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_f057e04541b64095, []int{3}
}
func (m *SignedData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignedData.Unmarshal(m, b)
}
func (m *SignedData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignedData.Marshal(b, m, deterministic)
}
func (dst *SignedData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignedData.Merge(dst, src)
}
func (m *SignedData) XXX_Size() int {
	return xxx_messageInfo_SignedData.Size(m)
}
func (m *SignedData) XXX_DiscardUnknown() {
	xxx_messageInfo_SignedData.DiscardUnknown(m)
}

var xxx_messageInfo_SignedData proto.InternalMessageInfo

func (m *SignedData) GetSenderPubkey() []byte {
	if m != nil {
		return m.SenderPubkey
	}
	return nil
}

func (m *SignedData) GetSerializedData() []byte {
	if m != nil {
		return m.SerializedData
	}
	return nil
}

func (m *SignedData) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type CidList struct {
	Cids                 []string `protobuf:"bytes,1,rep,name=cids,proto3" json:"cids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CidList) Reset()         { *m = CidList{} }
func (m *CidList) String() string { return proto.CompactTextString(m) }
func (*CidList) ProtoMessage()    {}
func (*CidList) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_f057e04541b64095, []int{4}
}
func (m *CidList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CidList.Unmarshal(m, b)
}
func (m *CidList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CidList.Marshal(b, m, deterministic)
}
func (dst *CidList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CidList.Merge(dst, src)
}
func (m *CidList) XXX_Size() int {
	return xxx_messageInfo_CidList.Size(m)
}
func (m *CidList) XXX_DiscardUnknown() {
	xxx_messageInfo_CidList.DiscardUnknown(m)
}

var xxx_messageInfo_CidList proto.InternalMessageInfo

func (m *CidList) GetCids() []string {
	if m != nil {
		return m.Cids
	}
	return nil
}

type Block struct {
	RawData              []byte   `protobuf:"bytes,1,opt,name=rawData,proto3" json:"rawData,omitempty"`
	Cid                  string   `protobuf:"bytes,2,opt,name=cid,proto3" json:"cid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Block) Reset()         { *m = Block{} }
func (m *Block) String() string { return proto.CompactTextString(m) }
func (*Block) ProtoMessage()    {}
func (*Block) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_f057e04541b64095, []int{5}
}
func (m *Block) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Block.Unmarshal(m, b)
}
func (m *Block) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Block.Marshal(b, m, deterministic)
}
func (dst *Block) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Block.Merge(dst, src)
}
func (m *Block) XXX_Size() int {
	return xxx_messageInfo_Block.Size(m)
}
func (m *Block) XXX_DiscardUnknown() {
	xxx_messageInfo_Block.DiscardUnknown(m)
}

var xxx_messageInfo_Block proto.InternalMessageInfo

func (m *Block) GetRawData() []byte {
	if m != nil {
		return m.RawData
	}
	return nil
}

func (m *Block) GetCid() string {
	if m != nil {
		return m.Cid
	}
	return ""
}

type Error struct {
	Code                 uint32   `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	ErrorMessage         string   `protobuf:"bytes,2,opt,name=errorMessage,proto3" json:"errorMessage,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_f057e04541b64095, []int{6}
}
func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (dst *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(dst, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func init() {
	proto.RegisterType((*Message)(nil), "Message")
	proto.RegisterType((*Envelope)(nil), "Envelope")
	proto.RegisterType((*Chat)(nil), "Chat")
	proto.RegisterType((*SignedData)(nil), "SignedData")
	proto.RegisterType((*CidList)(nil), "CidList")
	proto.RegisterType((*Block)(nil), "Block")
	proto.RegisterType((*Error)(nil), "Error")
	proto.RegisterEnum("Message_Type", Message_Type_name, Message_Type_value)
	proto.RegisterEnum("Chat_Flag", Chat_Flag_name, Chat_Flag_value)
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_message_f057e04541b64095) }

var fileDescriptor_message_f057e04541b64095 = []byte{
	// 635 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0xc1, 0x6e, 0xd3, 0x4c,
	0x10, 0xc7, 0xeb, 0xc4, 0x89, 0xe3, 0x49, 0xd2, 0x6f, 0xbb, 0xea, 0x87, 0x4c, 0x05, 0x25, 0xf8,
	0x80, 0xc2, 0xc5, 0x95, 0xd2, 0x0b, 0x37, 0xe4, 0x26, 0x4e, 0x6b, 0x35, 0xb1, 0xab, 0x8d, 0x29,
	0x2a, 0x97, 0xca, 0x89, 0xb7, 0xc6, 0xd4, 0xb5, 0x8d, 0xd7, 0x29, 0x0a, 0xef, 0x0a, 0x4f, 0xc1,
	0x8d, 0x0b, 0xda, 0xb5, 0x4d, 0x68, 0x39, 0x70, 0x9b, 0xf9, 0xcd, 0xec, 0xcc, 0xec, 0x7f, 0x06,
	0xfa, 0x77, 0x94, 0x31, 0x3f, 0xa4, 0x46, 0x96, 0xa7, 0x45, 0x7a, 0xf0, 0x34, 0x4c, 0xd3, 0x30,
	0xa6, 0x47, 0xc2, 0x5b, 0xae, 0x6f, 0x8e, 0xfc, 0x64, 0x53, 0x85, 0x5e, 0x3c, 0x0e, 0x15, 0xd1,
	0x1d, 0x65, 0x85, 0x7f, 0x97, 0x95, 0x09, 0xfa, 0xcf, 0x06, 0x28, 0xf3, 0xb2, 0x1a, 0x7e, 0x09,
	0x72, 0xb1, 0xc9, 0xa8, 0x26, 0x0d, 0xa4, 0xe1, 0xee, 0xa8, 0x6f, 0x54, 0xdc, 0xf0, 0x36, 0x19,
	0x25, 0x22, 0x84, 0x0d, 0x50, 0x32, 0x7f, 0x13, 0xa7, 0x7e, 0xa0, 0x35, 0x06, 0xd2, 0xb0, 0x3b,
	0xda, 0x37, 0xca, 0x0e, 0x46, 0xdd, 0xc1, 0x30, 0x93, 0x0d, 0xa9, 0x93, 0xf0, 0x33, 0x50, 0x73,
	0xfa, 0x79, 0x4d, 0x59, 0x61, 0x07, 0x5a, 0x73, 0x20, 0x0d, 0x5b, 0x64, 0x0b, 0xf0, 0x21, 0x40,
	0xc4, 0x08, 0x65, 0x59, 0x9a, 0x30, 0xaa, 0xc9, 0x03, 0x69, 0xd8, 0x21, 0x7f, 0x10, 0xfd, 0xbb,
	0x04, 0x32, 0x6f, 0x8e, 0x3b, 0x20, 0x5f, 0xd8, 0xce, 0x29, 0xda, 0xe1, 0xd6, 0xf8, 0xcc, 0xf4,
	0x90, 0x84, 0x01, 0xda, 0x53, 0x77, 0x36, 0x73, 0xdf, 0xa3, 0x06, 0xee, 0x41, 0xe7, 0x9d, 0x53,
	0x79, 0x4d, 0xfc, 0x1f, 0x74, 0xdd, 0xe9, 0x74, 0x66, 0x3b, 0xd6, 0xb5, 0x39, 0x3e, 0x47, 0x32,
	0xde, 0x83, 0x7e, 0x0d, 0x88, 0x35, 0x33, 0xaf, 0x50, 0x8b, 0xa3, 0xb9, 0x3b, 0xb1, 0x88, 0xe9,
	0xb9, 0xe4, 0xda, 0x9c, 0x4c, 0x50, 0x1b, 0xef, 0x03, 0xda, 0x22, 0x62, 0xcd, 0xdd, 0x4b, 0x0b,
	0x29, 0x58, 0x85, 0xd6, 0xc2, 0x73, 0x89, 0x85, 0x3a, 0xdc, 0x3c, 0x99, 0xb9, 0xe3, 0x73, 0xa4,
	0xf2, 0xe7, 0xde, 0x19, 0xb1, 0xcc, 0xc9, 0xb5, 0xed, 0x5c, 0xda, 0x9e, 0x85, 0x02, 0xde, 0xb5,
	0x42, 0x13, 0xd3, 0x33, 0x11, 0xc5, 0xff, 0xc3, 0x5e, 0x05, 0x4c, 0xc7, 0x71, 0x3d, 0xd3, 0xb3,
	0x5d, 0x07, 0xdd, 0x60, 0x80, 0x96, 0x45, 0x88, 0x4b, 0xd0, 0x8f, 0xa6, 0x1e, 0x40, 0xc7, 0x4a,
	0xee, 0x69, 0x9c, 0x66, 0x14, 0xeb, 0xa0, 0x54, 0x6b, 0x15, 0x0b, 0xe8, 0x8e, 0x3a, 0xf5, 0x02,
	0x48, 0x1d, 0xc0, 0x4f, 0xa0, 0x9d, 0xad, 0x97, 0xb7, 0x74, 0x23, 0xd4, 0xef, 0x91, 0xca, 0xe3,
	0x32, 0xb3, 0x28, 0x4c, 0xfc, 0x62, 0x9d, 0x53, 0x21, 0x73, 0x8f, 0x6c, 0x81, 0xfe, 0x4d, 0x02,
	0x79, 0xfc, 0xd1, 0x2f, 0x78, 0x5a, 0x55, 0xc9, 0x0e, 0x44, 0x13, 0x95, 0x6c, 0x01, 0xd6, 0x40,
	0x61, 0xeb, 0xe5, 0x27, 0xba, 0x2a, 0x44, 0x75, 0x95, 0xd4, 0x2e, 0x8f, 0xd4, 0xa3, 0x35, 0xcb,
	0x48, 0x3d, 0xd0, 0x1b, 0x50, 0x7f, 0x5f, 0x94, 0x58, 0x60, 0x77, 0x74, 0xf0, 0xd7, 0x45, 0x78,
	0x75, 0x06, 0xd9, 0x26, 0xe3, 0x43, 0x90, 0x6f, 0x62, 0x3f, 0xd4, 0x5a, 0xe2, 0xd8, 0xc0, 0xe0,
	0x03, 0x1a, 0xd3, 0xd8, 0x0f, 0x89, 0xe0, 0xfa, 0x6b, 0x90, 0xb9, 0x87, 0xbb, 0xa0, 0xcc, 0xad,
	0xc5, 0xc2, 0x3c, 0xb5, 0xd0, 0x0e, 0xdf, 0xb9, 0x77, 0x25, 0x2e, 0x41, 0xe2, 0x97, 0xc0, 0xc5,
	0x45, 0x0d, 0xfd, 0x1e, 0x60, 0x11, 0x85, 0x09, 0x0d, 0x26, 0x7e, 0xe1, 0x63, 0x1d, 0x7a, 0x8c,
	0x26, 0x01, 0xcd, 0x2f, 0x4a, 0xa5, 0x24, 0x21, 0xc7, 0x03, 0x86, 0x5f, 0xc1, 0x2e, 0xa3, 0x79,
	0xe4, 0xc7, 0xd1, 0xd7, 0xf2, 0x55, 0xa5, 0xe7, 0x23, 0xfa, 0x0f, 0x5d, 0x9f, 0x83, 0x32, 0x8e,
	0x82, 0x59, 0xc4, 0x0a, 0x8c, 0x41, 0x5e, 0x45, 0x01, 0xd3, 0xa4, 0x41, 0x73, 0xa8, 0x12, 0x61,
	0xeb, 0xc7, 0xd0, 0x3a, 0x89, 0xd3, 0xd5, 0x2d, 0x97, 0x2f, 0xf7, 0xbf, 0x88, 0x36, 0xe5, 0x30,
	0xb5, 0x8b, 0x11, 0x34, 0x57, 0x51, 0x50, 0xc9, 0xcd, 0x4d, 0xfd, 0x2d, 0xb4, 0xac, 0x3c, 0x4f,
	0x73, 0x51, 0x31, 0x0d, 0xca, 0x5b, 0xe8, 0x13, 0x61, 0xf3, 0xaf, 0x51, 0x1e, 0xac, 0xee, 0xa2,
	0x7a, 0xf7, 0x80, 0x9d, 0xc8, 0x1f, 0x1a, 0xd9, 0x72, 0xd9, 0x16, 0xe2, 0x1f, 0xff, 0x0a, 0x00,
	0x00, 0xff, 0xff, 0x57, 0x40, 0x67, 0x5d, 0x2a, 0x04, 0x00, 0x00,
}
