// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import any "github.com/golang/protobuf/ptypes/any"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Message_Type int32

const (
	Message_PING                     Message_Type = 0
	Message_PONG                     Message_Type = 1
	Message_THREAD_ENVELOPE          Message_Type = 10
	Message_CAFE_CHALLENGE           Message_Type = 50
	Message_CAFE_NONCE               Message_Type = 51
	Message_CAFE_REGISTRATION        Message_Type = 52
	Message_CAFE_SESSION             Message_Type = 53
	Message_CAFE_REFRESH_SESSION     Message_Type = 54
	Message_CAFE_STORE               Message_Type = 55
	Message_CAFE_OBJECT              Message_Type = 56
	Message_CAFE_OBJECT_LIST         Message_Type = 57
	Message_CAFE_STORE_THREAD        Message_Type = 58
	Message_CAFE_STORED              Message_Type = 59
	Message_CAFE_DELIVER_MESSAGE     Message_Type = 60
	Message_CAFE_CHECK_MESSAGES      Message_Type = 61
	Message_CAFE_MESSAGES            Message_Type = 62
	Message_CAFE_DELETE_MESSAGES     Message_Type = 63
	Message_CAFE_DELETE_MESSAGES_ACK Message_Type = 64
	Message_CAFE_YOU_HAVE_MAIL       Message_Type = 65
	Message_CAFE_PUBLISH_CONTACT     Message_Type = 66
	Message_CAFE_PUBLISH_CONTACT_ACK Message_Type = 67
	Message_CAFE_FIND_CONTACT        Message_Type = 68
	Message_CAFE_FIND_CONTACT_RES    Message_Type = 69
	Message_CAFE_PUBSUB_CONTACT_REQ  Message_Type = 100
	Message_CAFE_PUBSUB_CONTACT_RES  Message_Type = 101
	Message_ERROR                    Message_Type = 500
)

var Message_Type_name = map[int32]string{
	0:   "PING",
	1:   "PONG",
	10:  "THREAD_ENVELOPE",
	50:  "CAFE_CHALLENGE",
	51:  "CAFE_NONCE",
	52:  "CAFE_REGISTRATION",
	53:  "CAFE_SESSION",
	54:  "CAFE_REFRESH_SESSION",
	55:  "CAFE_STORE",
	56:  "CAFE_OBJECT",
	57:  "CAFE_OBJECT_LIST",
	58:  "CAFE_STORE_THREAD",
	59:  "CAFE_STORED",
	60:  "CAFE_DELIVER_MESSAGE",
	61:  "CAFE_CHECK_MESSAGES",
	62:  "CAFE_MESSAGES",
	63:  "CAFE_DELETE_MESSAGES",
	64:  "CAFE_DELETE_MESSAGES_ACK",
	65:  "CAFE_YOU_HAVE_MAIL",
	66:  "CAFE_PUBLISH_CONTACT",
	67:  "CAFE_PUBLISH_CONTACT_ACK",
	68:  "CAFE_FIND_CONTACT",
	69:  "CAFE_FIND_CONTACT_RES",
	100: "CAFE_PUBSUB_CONTACT_REQ",
	101: "CAFE_PUBSUB_CONTACT_RES",
	500: "ERROR",
}
var Message_Type_value = map[string]int32{
	"PING":                     0,
	"PONG":                     1,
	"THREAD_ENVELOPE":          10,
	"CAFE_CHALLENGE":           50,
	"CAFE_NONCE":               51,
	"CAFE_REGISTRATION":        52,
	"CAFE_SESSION":             53,
	"CAFE_REFRESH_SESSION":     54,
	"CAFE_STORE":               55,
	"CAFE_OBJECT":              56,
	"CAFE_OBJECT_LIST":         57,
	"CAFE_STORE_THREAD":        58,
	"CAFE_STORED":              59,
	"CAFE_DELIVER_MESSAGE":     60,
	"CAFE_CHECK_MESSAGES":      61,
	"CAFE_MESSAGES":            62,
	"CAFE_DELETE_MESSAGES":     63,
	"CAFE_DELETE_MESSAGES_ACK": 64,
	"CAFE_YOU_HAVE_MAIL":       65,
	"CAFE_PUBLISH_CONTACT":     66,
	"CAFE_PUBLISH_CONTACT_ACK": 67,
	"CAFE_FIND_CONTACT":        68,
	"CAFE_FIND_CONTACT_RES":    69,
	"CAFE_PUBSUB_CONTACT_REQ":  100,
	"CAFE_PUBSUB_CONTACT_RES":  101,
	"ERROR":                    500,
}

func (x Message_Type) String() string {
	return proto.EnumName(Message_Type_name, int32(x))
}
func (Message_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_message_c27d54e8d18b30d0, []int{0, 0}
}

type Message struct {
	Type                 Message_Type `protobuf:"varint,1,opt,name=type,proto3,enum=Message_Type" json:"type,omitempty"`
	Payload              *any.Any     `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	RequestId            int32        `protobuf:"varint,3,opt,name=requestId,proto3" json:"requestId,omitempty"`
	IsResponse           bool         `protobuf:"varint,4,opt,name=isResponse,proto3" json:"isResponse,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_c27d54e8d18b30d0, []int{0}
}
func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (dst *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(dst, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetType() Message_Type {
	if m != nil {
		return m.Type
	}
	return Message_PING
}

func (m *Message) GetPayload() *any.Any {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *Message) GetRequestId() int32 {
	if m != nil {
		return m.RequestId
	}
	return 0
}

func (m *Message) GetIsResponse() bool {
	if m != nil {
		return m.IsResponse
	}
	return false
}

type Envelope struct {
	Message              *Message `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Sig                  []byte   `protobuf:"bytes,2,opt,name=sig,proto3" json:"sig,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Envelope) Reset()         { *m = Envelope{} }
func (m *Envelope) String() string { return proto.CompactTextString(m) }
func (*Envelope) ProtoMessage()    {}
func (*Envelope) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_c27d54e8d18b30d0, []int{1}
}
func (m *Envelope) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Envelope.Unmarshal(m, b)
}
func (m *Envelope) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Envelope.Marshal(b, m, deterministic)
}
func (dst *Envelope) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Envelope.Merge(dst, src)
}
func (m *Envelope) XXX_Size() int {
	return xxx_messageInfo_Envelope.Size(m)
}
func (m *Envelope) XXX_DiscardUnknown() {
	xxx_messageInfo_Envelope.DiscardUnknown(m)
}

var xxx_messageInfo_Envelope proto.InternalMessageInfo

func (m *Envelope) GetMessage() *Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *Envelope) GetSig() []byte {
	if m != nil {
		return m.Sig
	}
	return nil
}

type Error struct {
	Code                 uint32   `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_c27d54e8d18b30d0, []int{2}
}
func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (dst *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(dst, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*Message)(nil), "Message")
	proto.RegisterType((*Envelope)(nil), "Envelope")
	proto.RegisterType((*Error)(nil), "Error")
	proto.RegisterEnum("Message_Type", Message_Type_name, Message_Type_value)
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_message_c27d54e8d18b30d0) }

var fileDescriptor_message_c27d54e8d18b30d0 = []byte{
	// 538 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x93, 0xdb, 0x6e, 0xda, 0x4c,
	0x10, 0xc7, 0x3f, 0x27, 0xe6, 0x0b, 0x99, 0x04, 0xb2, 0x99, 0x90, 0xc6, 0x69, 0xa3, 0x8a, 0x72,
	0xc5, 0x95, 0x23, 0x91, 0xa6, 0xe7, 0x43, 0x8c, 0x19, 0xc0, 0x8d, 0xb1, 0xe9, 0xae, 0x41, 0x6a,
	0x6f, 0x2c, 0x28, 0x5b, 0x14, 0x89, 0x62, 0x17, 0x93, 0x4a, 0x3c, 0x5b, 0x5f, 0xa4, 0x0f, 0xd2,
	0x07, 0xa8, 0x58, 0xb0, 0x83, 0x7a, 0xb8, 0xdb, 0xfd, 0xfd, 0x66, 0xfe, 0x63, 0x4b, 0xb3, 0x50,
	0xf8, 0x22, 0x93, 0x64, 0x30, 0x96, 0x66, 0x3c, 0x8b, 0xe6, 0xd1, 0xfd, 0xd3, 0x71, 0x14, 0x8d,
	0x27, 0xf2, 0x5c, 0xdd, 0x86, 0xb7, 0x9f, 0xcf, 0x07, 0xd3, 0xc5, 0x4a, 0x55, 0x7e, 0xe4, 0x60,
	0xa7, 0xb3, 0x2a, 0xc6, 0x47, 0xa0, 0xcf, 0x17, 0xb1, 0x34, 0xb4, 0xb2, 0x56, 0x2d, 0xd6, 0x0a,
	0xe6, 0x9a, 0x9b, 0xc1, 0x22, 0x96, 0x5c, 0x29, 0x34, 0x61, 0x27, 0x1e, 0x2c, 0x26, 0xd1, 0x60,
	0x64, 0x6c, 0x95, 0xb5, 0xea, 0x5e, 0xad, 0x64, 0xae, 0xb2, 0xcd, 0x34, 0xdb, 0xb4, 0xa6, 0x0b,
	0x9e, 0x16, 0xe1, 0x19, 0xec, 0xce, 0xe4, 0xd7, 0x5b, 0x99, 0xcc, 0x9d, 0x91, 0xb1, 0x5d, 0xd6,
	0xaa, 0x39, 0x7e, 0x07, 0xf0, 0x21, 0xc0, 0x4d, 0xc2, 0x65, 0x12, 0x47, 0xd3, 0x44, 0x1a, 0x7a,
	0x59, 0xab, 0xe6, 0xf9, 0x06, 0xa9, 0x7c, 0xd7, 0x41, 0x5f, 0x0e, 0xc7, 0x3c, 0xe8, 0x5d, 0xc7,
	0x6b, 0xb1, 0xff, 0xd4, 0xc9, 0xf7, 0x5a, 0x4c, 0xc3, 0x23, 0x38, 0x08, 0xda, 0x9c, 0xac, 0x46,
	0x48, 0x5e, 0x9f, 0x5c, 0xbf, 0x4b, 0x0c, 0x10, 0xa1, 0x68, 0x5b, 0x4d, 0x0a, 0xed, 0xb6, 0xe5,
	0xba, 0xe4, 0xb5, 0x88, 0xd5, 0xb0, 0x08, 0xa0, 0x98, 0xe7, 0x7b, 0x36, 0xb1, 0x0b, 0x3c, 0x86,
	0x43, 0x75, 0xe7, 0xd4, 0x72, 0x44, 0xc0, 0xad, 0xc0, 0xf1, 0x3d, 0xf6, 0x18, 0x19, 0xec, 0x2b,
	0x2c, 0x48, 0x88, 0x25, 0xb9, 0x44, 0x03, 0x4a, 0xeb, 0xc2, 0x26, 0x27, 0xd1, 0xce, 0xcc, 0x93,
	0x2c, 0x52, 0x04, 0x3e, 0x27, 0xf6, 0x14, 0x0f, 0x60, 0x4f, 0xdd, 0xfd, 0xfa, 0x3b, 0xb2, 0x03,
	0xf6, 0x0c, 0x4b, 0xc0, 0x36, 0x40, 0xe8, 0x3a, 0x22, 0x60, 0xcf, 0xb3, 0xc9, 0xaa, 0x2d, 0x5c,
	0x7d, 0x3d, 0x7b, 0x91, 0x75, 0x2b, 0xdc, 0x60, 0x2f, 0xb3, 0xc1, 0x0d, 0x72, 0x9d, 0x3e, 0xf1,
	0xb0, 0x43, 0x42, 0x58, 0x2d, 0x62, 0xaf, 0xf0, 0x04, 0x8e, 0xd6, 0xff, 0x47, 0xf6, 0x75, 0xca,
	0x05, 0x7b, 0x8d, 0x87, 0x50, 0x50, 0x22, 0x43, 0x6f, 0x36, 0x53, 0x28, 0xd8, 0x30, 0x6f, 0xf1,
	0x0c, 0x8c, 0xbf, 0x99, 0xd0, 0xb2, 0xaf, 0xd9, 0x15, 0xde, 0x03, 0x54, 0xf6, 0x83, 0xdf, 0x0b,
	0xdb, 0x56, 0x9f, 0xc2, 0x8e, 0xe5, 0xb8, 0xcc, 0xca, 0xf2, 0xba, 0xbd, 0xba, 0xeb, 0x88, 0x76,
	0x68, 0xfb, 0x5e, 0x60, 0xd9, 0x01, 0xab, 0x67, 0x79, 0xbf, 0x19, 0x95, 0x67, 0x67, 0x7f, 0xdd,
	0x74, 0xbc, 0x46, 0xd6, 0xd4, 0xc0, 0x53, 0x38, 0xfe, 0x03, 0x87, 0x9c, 0x04, 0x23, 0x7c, 0x00,
	0x27, 0x69, 0x9e, 0xe8, 0xd5, 0x37, 0xe4, 0x7b, 0x36, 0xfa, 0xb7, 0x14, 0x4c, 0x22, 0x40, 0x8e,
	0x38, 0xf7, 0x39, 0xfb, 0xb9, 0x5d, 0xb9, 0x82, 0x3c, 0x4d, 0xbf, 0xc9, 0x49, 0x14, 0x4b, 0xac,
	0xc0, 0xce, 0xfa, 0x49, 0xa8, 0xed, 0xde, 0xab, 0xe5, 0xd3, 0xed, 0xe6, 0xa9, 0x40, 0x06, 0xdb,
	0xc9, 0xcd, 0x58, 0xed, 0xf5, 0x3e, 0x5f, 0x1e, 0x2b, 0x97, 0x90, 0xa3, 0xd9, 0x2c, 0x9a, 0x21,
	0x82, 0xfe, 0x29, 0x1a, 0xad, 0x7a, 0x0b, 0x5c, 0x9d, 0xd1, 0xb8, 0x8b, 0x5c, 0xb6, 0xec, 0x66,
	0x41, 0x75, 0xfd, 0xe3, 0x56, 0x3c, 0x1c, 0xfe, 0xaf, 0x5e, 0xc4, 0xc5, 0xaf, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xe1, 0x1c, 0xb1, 0x92, 0x8c, 0x03, 0x00, 0x00,
}
