// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mobile.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MobileEventType int32

const (
	MobileEventType_NODE_START     MobileEventType = 0
	MobileEventType_NODE_ONLINE    MobileEventType = 1
	MobileEventType_NODE_STOP      MobileEventType = 2
	MobileEventType_WALLET_UPDATE  MobileEventType = 10
	MobileEventType_THREAD_UPDATE  MobileEventType = 11
	MobileEventType_NOTIFICATION   MobileEventType = 12
	MobileEventType_QUERY_RESPONSE MobileEventType = 20
)

var MobileEventType_name = map[int32]string{
	0:  "NODE_START",
	1:  "NODE_ONLINE",
	2:  "NODE_STOP",
	10: "WALLET_UPDATE",
	11: "THREAD_UPDATE",
	12: "NOTIFICATION",
	20: "QUERY_RESPONSE",
}
var MobileEventType_value = map[string]int32{
	"NODE_START":     0,
	"NODE_ONLINE":    1,
	"NODE_STOP":      2,
	"WALLET_UPDATE":  10,
	"THREAD_UPDATE":  11,
	"NOTIFICATION":   12,
	"QUERY_RESPONSE": 20,
}

func (x MobileEventType) String() string {
	return proto.EnumName(MobileEventType_name, int32(x))
}
func (MobileEventType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_mobile_086994705975b315, []int{0}
}

type MobileQueryEvent_Type int32

const (
	MobileQueryEvent_DATA  MobileQueryEvent_Type = 0
	MobileQueryEvent_DONE  MobileQueryEvent_Type = 1
	MobileQueryEvent_ERROR MobileQueryEvent_Type = 2
)

var MobileQueryEvent_Type_name = map[int32]string{
	0: "DATA",
	1: "DONE",
	2: "ERROR",
}
var MobileQueryEvent_Type_value = map[string]int32{
	"DATA":  0,
	"DONE":  1,
	"ERROR": 2,
}

func (x MobileQueryEvent_Type) String() string {
	return proto.EnumName(MobileQueryEvent_Type_name, int32(x))
}
func (MobileQueryEvent_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_mobile_086994705975b315, []int{1, 0}
}

type MobileWalletAccount struct {
	Seed                 string   `protobuf:"bytes,1,opt,name=seed,proto3" json:"seed,omitempty"`
	Address              string   `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MobileWalletAccount) Reset()         { *m = MobileWalletAccount{} }
func (m *MobileWalletAccount) String() string { return proto.CompactTextString(m) }
func (*MobileWalletAccount) ProtoMessage()    {}
func (*MobileWalletAccount) Descriptor() ([]byte, []int) {
	return fileDescriptor_mobile_086994705975b315, []int{0}
}
func (m *MobileWalletAccount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MobileWalletAccount.Unmarshal(m, b)
}
func (m *MobileWalletAccount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MobileWalletAccount.Marshal(b, m, deterministic)
}
func (dst *MobileWalletAccount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MobileWalletAccount.Merge(dst, src)
}
func (m *MobileWalletAccount) XXX_Size() int {
	return xxx_messageInfo_MobileWalletAccount.Size(m)
}
func (m *MobileWalletAccount) XXX_DiscardUnknown() {
	xxx_messageInfo_MobileWalletAccount.DiscardUnknown(m)
}

var xxx_messageInfo_MobileWalletAccount proto.InternalMessageInfo

func (m *MobileWalletAccount) GetSeed() string {
	if m != nil {
		return m.Seed
	}
	return ""
}

func (m *MobileWalletAccount) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type MobileQueryEvent struct {
	Id                   string                `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type                 MobileQueryEvent_Type `protobuf:"varint,2,opt,name=type,proto3,enum=MobileQueryEvent_Type" json:"type,omitempty"`
	Data                 *QueryResult          `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Error                *Error                `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *MobileQueryEvent) Reset()         { *m = MobileQueryEvent{} }
func (m *MobileQueryEvent) String() string { return proto.CompactTextString(m) }
func (*MobileQueryEvent) ProtoMessage()    {}
func (*MobileQueryEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_mobile_086994705975b315, []int{1}
}
func (m *MobileQueryEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MobileQueryEvent.Unmarshal(m, b)
}
func (m *MobileQueryEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MobileQueryEvent.Marshal(b, m, deterministic)
}
func (dst *MobileQueryEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MobileQueryEvent.Merge(dst, src)
}
func (m *MobileQueryEvent) XXX_Size() int {
	return xxx_messageInfo_MobileQueryEvent.Size(m)
}
func (m *MobileQueryEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_MobileQueryEvent.DiscardUnknown(m)
}

var xxx_messageInfo_MobileQueryEvent proto.InternalMessageInfo

func (m *MobileQueryEvent) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *MobileQueryEvent) GetType() MobileQueryEvent_Type {
	if m != nil {
		return m.Type
	}
	return MobileQueryEvent_DATA
}

func (m *MobileQueryEvent) GetData() *QueryResult {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *MobileQueryEvent) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func init() {
	proto.RegisterType((*MobileWalletAccount)(nil), "MobileWalletAccount")
	proto.RegisterType((*MobileQueryEvent)(nil), "MobileQueryEvent")
	proto.RegisterEnum("MobileEventType", MobileEventType_name, MobileEventType_value)
	proto.RegisterEnum("MobileQueryEvent_Type", MobileQueryEvent_Type_name, MobileQueryEvent_Type_value)
}

func init() { proto.RegisterFile("mobile.proto", fileDescriptor_mobile_086994705975b315) }

var fileDescriptor_mobile_086994705975b315 = []byte{
	// 355 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x91, 0xdf, 0x8a, 0xda, 0x40,
	0x14, 0xc6, 0x4d, 0x1a, 0x6d, 0x3d, 0xf9, 0xe3, 0x74, 0x2c, 0x25, 0x94, 0x5e, 0x88, 0x50, 0x10,
	0x2f, 0x72, 0x61, 0x9f, 0x60, 0x6a, 0xa6, 0x6c, 0xc0, 0xcd, 0xe8, 0x38, 0x22, 0xbb, 0x37, 0x92,
	0x98, 0x61, 0x09, 0x44, 0x93, 0x4d, 0xc6, 0x65, 0x7d, 0x88, 0x7d, 0x9c, 0x7d, 0xbf, 0x25, 0xa3,
	0xde, 0xec, 0xdd, 0x7c, 0xdf, 0xf9, 0x7d, 0xdf, 0x1c, 0x38, 0xe0, 0x1c, 0xca, 0x34, 0x2f, 0x64,
	0x50, 0xd5, 0xa5, 0x2a, 0x7f, 0xd9, 0xcf, 0x27, 0x59, 0x9f, 0xaf, 0xc2, 0x3d, 0xc8, 0xa6, 0x49,
	0x9e, 0xae, 0xb3, 0xf1, 0x1c, 0x86, 0xf7, 0x9a, 0xdd, 0x26, 0x45, 0x21, 0x15, 0xd9, 0xef, 0xcb,
	0xd3, 0x51, 0x61, 0x0c, 0x56, 0x23, 0x65, 0xe6, 0x1b, 0x23, 0x63, 0xd2, 0xe7, 0xfa, 0x8d, 0x7d,
	0xf8, 0x9a, 0x64, 0x59, 0x2d, 0x9b, 0xc6, 0x37, 0xb5, 0x7d, 0x93, 0xe3, 0x77, 0x03, 0xd0, 0xa5,
	0x65, 0xd5, 0xfe, 0x44, 0x5f, 0xe4, 0x51, 0x61, 0x0f, 0xcc, 0xfc, 0x56, 0x60, 0xe6, 0x19, 0x9e,
	0x82, 0xa5, 0xce, 0x95, 0xd4, 0x59, 0x6f, 0xf6, 0x33, 0xf8, 0x1c, 0x08, 0xc4, 0xb9, 0x92, 0x5c,
	0x33, 0x78, 0x04, 0x56, 0x96, 0xa8, 0xc4, 0xff, 0x32, 0x32, 0x26, 0xf6, 0xcc, 0x09, 0x34, 0xc5,
	0x65, 0x73, 0x2a, 0x14, 0xd7, 0x13, 0xfc, 0x1b, 0xba, 0xb2, 0xae, 0xcb, 0xda, 0xb7, 0x34, 0xd2,
	0x0b, 0x68, 0xab, 0xf8, 0xc5, 0x1c, 0xff, 0x01, 0xab, 0x6d, 0xc3, 0xdf, 0xc0, 0x0a, 0x89, 0x20,
	0xa8, 0xa3, 0x5f, 0x2c, 0xa6, 0xc8, 0xc0, 0x7d, 0xe8, 0x52, 0xce, 0x19, 0x47, 0xe6, 0xf4, 0xcd,
	0x80, 0xc1, 0x65, 0x0d, 0xbd, 0x81, 0x8e, 0x78, 0x00, 0x31, 0x0b, 0xe9, 0x6e, 0x2d, 0x08, 0x17,
	0xa8, 0x83, 0x07, 0x60, 0x6b, 0xcd, 0xe2, 0x45, 0xa4, 0xf3, 0x2e, 0xf4, 0xaf, 0x00, 0x5b, 0x22,
	0x13, 0x7f, 0x07, 0x77, 0x4b, 0x16, 0x0b, 0x2a, 0x76, 0x9b, 0x65, 0x48, 0x04, 0x45, 0xd0, 0x5a,
	0xe2, 0x8e, 0x53, 0x12, 0xde, 0x2c, 0x1b, 0x23, 0x70, 0x62, 0x26, 0xa2, 0xff, 0xd1, 0x9c, 0x88,
	0x88, 0xc5, 0xc8, 0xc1, 0x18, 0xbc, 0xd5, 0x86, 0xf2, 0x87, 0x1d, 0xa7, 0xeb, 0x25, 0x8b, 0xd7,
	0x14, 0xfd, 0xf8, 0x37, 0x04, 0x37, 0x2f, 0x03, 0x25, 0x5f, 0x95, 0x3e, 0x5e, 0xfa, 0x68, 0x56,
	0x69, 0xda, 0xd3, 0x87, 0xfa, 0xfb, 0x11, 0x00, 0x00, 0xff, 0xff, 0x25, 0x69, 0xd2, 0x42, 0xd4,
	0x01, 0x00, 0x00,
}
