// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mobile.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MobileEvent_Type int32

const (
	MobileEvent_NODE_START     MobileEvent_Type = 0
	MobileEvent_NODE_ONLINE    MobileEvent_Type = 1
	MobileEvent_NODE_STOP      MobileEvent_Type = 2
	MobileEvent_WALLET_UPDATE  MobileEvent_Type = 10
	MobileEvent_THREAD_UPDATE  MobileEvent_Type = 11
	MobileEvent_NOTIFICATION   MobileEvent_Type = 12
	MobileEvent_QUERY_RESPONSE MobileEvent_Type = 20
)

var MobileEvent_Type_name = map[int32]string{
	0:  "NODE_START",
	1:  "NODE_ONLINE",
	2:  "NODE_STOP",
	10: "WALLET_UPDATE",
	11: "THREAD_UPDATE",
	12: "NOTIFICATION",
	20: "QUERY_RESPONSE",
}
var MobileEvent_Type_value = map[string]int32{
	"NODE_START":     0,
	"NODE_ONLINE":    1,
	"NODE_STOP":      2,
	"WALLET_UPDATE":  10,
	"THREAD_UPDATE":  11,
	"NOTIFICATION":   12,
	"QUERY_RESPONSE": 20,
}

func (x MobileEvent_Type) String() string {
	return proto.EnumName(MobileEvent_Type_name, int32(x))
}
func (MobileEvent_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_mobile_2b2a252a7aea1b2f, []int{2, 0}
}

type MobilePreparedFiles struct {
	Dir                  *Directory        `protobuf:"bytes,1,opt,name=dir,proto3" json:"dir,omitempty"`
	Pin                  map[string]string `protobuf:"bytes,2,rep,name=pin,proto3" json:"pin,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *MobilePreparedFiles) Reset()         { *m = MobilePreparedFiles{} }
func (m *MobilePreparedFiles) String() string { return proto.CompactTextString(m) }
func (*MobilePreparedFiles) ProtoMessage()    {}
func (*MobilePreparedFiles) Descriptor() ([]byte, []int) {
	return fileDescriptor_mobile_2b2a252a7aea1b2f, []int{0}
}
func (m *MobilePreparedFiles) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MobilePreparedFiles.Unmarshal(m, b)
}
func (m *MobilePreparedFiles) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MobilePreparedFiles.Marshal(b, m, deterministic)
}
func (dst *MobilePreparedFiles) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MobilePreparedFiles.Merge(dst, src)
}
func (m *MobilePreparedFiles) XXX_Size() int {
	return xxx_messageInfo_MobilePreparedFiles.Size(m)
}
func (m *MobilePreparedFiles) XXX_DiscardUnknown() {
	xxx_messageInfo_MobilePreparedFiles.DiscardUnknown(m)
}

var xxx_messageInfo_MobilePreparedFiles proto.InternalMessageInfo

func (m *MobilePreparedFiles) GetDir() *Directory {
	if m != nil {
		return m.Dir
	}
	return nil
}

func (m *MobilePreparedFiles) GetPin() map[string]string {
	if m != nil {
		return m.Pin
	}
	return nil
}

type MobileFileData struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MobileFileData) Reset()         { *m = MobileFileData{} }
func (m *MobileFileData) String() string { return proto.CompactTextString(m) }
func (*MobileFileData) ProtoMessage()    {}
func (*MobileFileData) Descriptor() ([]byte, []int) {
	return fileDescriptor_mobile_2b2a252a7aea1b2f, []int{1}
}
func (m *MobileFileData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MobileFileData.Unmarshal(m, b)
}
func (m *MobileFileData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MobileFileData.Marshal(b, m, deterministic)
}
func (dst *MobileFileData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MobileFileData.Merge(dst, src)
}
func (m *MobileFileData) XXX_Size() int {
	return xxx_messageInfo_MobileFileData.Size(m)
}
func (m *MobileFileData) XXX_DiscardUnknown() {
	xxx_messageInfo_MobileFileData.DiscardUnknown(m)
}

var xxx_messageInfo_MobileFileData proto.InternalMessageInfo

func (m *MobileFileData) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type MobileEvent struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MobileEvent) Reset()         { *m = MobileEvent{} }
func (m *MobileEvent) String() string { return proto.CompactTextString(m) }
func (*MobileEvent) ProtoMessage()    {}
func (*MobileEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_mobile_2b2a252a7aea1b2f, []int{2}
}
func (m *MobileEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MobileEvent.Unmarshal(m, b)
}
func (m *MobileEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MobileEvent.Marshal(b, m, deterministic)
}
func (dst *MobileEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MobileEvent.Merge(dst, src)
}
func (m *MobileEvent) XXX_Size() int {
	return xxx_messageInfo_MobileEvent.Size(m)
}
func (m *MobileEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_MobileEvent.DiscardUnknown(m)
}

var xxx_messageInfo_MobileEvent proto.InternalMessageInfo

func (m *MobileEvent) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MobileEvent) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*MobilePreparedFiles)(nil), "MobilePreparedFiles")
	proto.RegisterMapType((map[string]string)(nil), "MobilePreparedFiles.PinEntry")
	proto.RegisterType((*MobileFileData)(nil), "MobileFileData")
	proto.RegisterType((*MobileEvent)(nil), "MobileEvent")
	proto.RegisterEnum("MobileEvent_Type", MobileEvent_Type_name, MobileEvent_Type_value)
}

func init() { proto.RegisterFile("mobile.proto", fileDescriptor_mobile_2b2a252a7aea1b2f) }

var fileDescriptor_mobile_2b2a252a7aea1b2f = []byte{
	// 330 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0xc1, 0x4f, 0xfa, 0x30,
	0x1c, 0xc5, 0x7f, 0xdb, 0xf8, 0x19, 0xf9, 0x6e, 0x60, 0xad, 0x1c, 0x08, 0xd1, 0x84, 0xec, 0xc4,
	0x69, 0x26, 0x98, 0x18, 0xe3, 0x6d, 0xba, 0x12, 0x97, 0xe0, 0x36, 0x4b, 0x89, 0xd1, 0x0b, 0x29,
	0xd2, 0x43, 0xe3, 0xd8, 0x96, 0x3a, 0x30, 0x5c, 0xfd, 0x3b, 0xfc, 0x4b, 0xfc, 0xeb, 0x4c, 0x3b,
	0xb8, 0x79, 0x7b, 0xef, 0xd3, 0xf7, 0x5e, 0x0f, 0x5f, 0xf0, 0xd6, 0xe5, 0x52, 0xe6, 0x22, 0xa8,
	0x54, 0x59, 0x97, 0x03, 0xd8, 0x4a, 0xf1, 0xd9, 0x68, 0xff, 0xdb, 0x82, 0xb3, 0x47, 0xf3, 0x98,
	0x29, 0x51, 0x71, 0x25, 0x56, 0x13, 0x99, 0x8b, 0x0f, 0x7c, 0x0e, 0xce, 0x4a, 0xaa, 0xbe, 0x35,
	0xb4, 0x46, 0xee, 0x18, 0x82, 0x48, 0x2a, 0xf1, 0x56, 0x97, 0x6a, 0x47, 0x35, 0xc6, 0x97, 0xe0,
	0x54, 0xb2, 0xe8, 0xdb, 0x43, 0x67, 0xe4, 0x8e, 0x2f, 0x82, 0x3f, 0x06, 0x82, 0x4c, 0x16, 0xa4,
	0xa8, 0x75, 0xa1, 0x92, 0xc5, 0xe0, 0x1a, 0x8e, 0x0f, 0x00, 0x23, 0x70, 0xde, 0xc5, 0xce, 0x4c,
	0xb7, 0xa9, 0x96, 0xb8, 0x07, 0xff, 0xb7, 0x3c, 0xdf, 0x88, 0xbe, 0x6d, 0x58, 0x63, 0x6e, 0xed,
	0x1b, 0xcb, 0xf7, 0xa1, 0xdb, 0x8c, 0xeb, 0xd1, 0x88, 0xd7, 0x5c, 0xb7, 0x37, 0x2a, 0x3f, 0xb4,
	0x37, 0x2a, 0xf7, 0x7f, 0x2c, 0x70, 0x9b, 0x10, 0xd9, 0x8a, 0xa2, 0xc6, 0x18, 0x5a, 0x05, 0x5f,
	0x8b, 0x7d, 0xc4, 0x68, 0xcd, 0x56, 0xbc, 0xe6, 0xe6, 0x03, 0x8f, 0x1a, 0xed, 0x7f, 0x59, 0xd0,
	0x62, 0xbb, 0x4a, 0xe0, 0x2e, 0x40, 0x92, 0x46, 0x64, 0x31, 0x63, 0x21, 0x65, 0xe8, 0x1f, 0x3e,
	0x01, 0xd7, 0xf8, 0x34, 0x99, 0xc6, 0x09, 0x41, 0x16, 0xee, 0x40, 0x7b, 0x1f, 0x48, 0x33, 0x64,
	0xe3, 0x53, 0xe8, 0x3c, 0x87, 0xd3, 0x29, 0x61, 0x8b, 0x79, 0x16, 0x85, 0x8c, 0x20, 0xd0, 0x88,
	0x3d, 0x50, 0x12, 0x46, 0x07, 0xe4, 0x62, 0x04, 0x5e, 0x92, 0xb2, 0x78, 0x12, 0xdf, 0x87, 0x2c,
	0x4e, 0x13, 0xe4, 0x61, 0x0c, 0xdd, 0xa7, 0x39, 0xa1, 0x2f, 0x0b, 0x4a, 0x66, 0x59, 0x9a, 0xcc,
	0x08, 0xea, 0xdd, 0xb5, 0x5e, 0xed, 0x6a, 0xb9, 0x3c, 0x32, 0xc7, 0xb8, 0xfa, 0x0d, 0x00, 0x00,
	0xff, 0xff, 0xc6, 0x85, 0xac, 0xa4, 0xa8, 0x01, 0x00, 0x00,
}
