// Code generated by protoc-gen-go. DO NOT EDIT.
// source: search.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import any "github.com/golang/protobuf/ptypes/any"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type QueryType int32

const (
	QueryType_BACKUPS  QueryType = 0
	QueryType_CONTACTS QueryType = 1
)

var QueryType_name = map[int32]string{
	0: "BACKUPS",
	1: "CONTACTS",
}
var QueryType_value = map[string]int32{
	"BACKUPS":  0,
	"CONTACTS": 1,
}

func (x QueryType) String() string {
	return proto.EnumName(QueryType_name, int32(x))
}
func (QueryType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_search_a18b88daa5ffd15d, []int{0}
}

type PubSubQuery_ResponseType int32

const (
	PubSubQuery_P2P    PubSubQuery_ResponseType = 0
	PubSubQuery_PUBSUB PubSubQuery_ResponseType = 1
)

var PubSubQuery_ResponseType_name = map[int32]string{
	0: "P2P",
	1: "PUBSUB",
}
var PubSubQuery_ResponseType_value = map[string]int32{
	"P2P":    0,
	"PUBSUB": 1,
}

func (x PubSubQuery_ResponseType) String() string {
	return proto.EnumName(PubSubQuery_ResponseType_name, int32(x))
}
func (PubSubQuery_ResponseType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_search_a18b88daa5ffd15d, []int{2, 0}
}

type QueryOptions struct {
	Local                bool     `protobuf:"varint,1,opt,name=local,proto3" json:"local,omitempty"`
	Limit                int32    `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Wait                 int32    `protobuf:"varint,3,opt,name=wait,proto3" json:"wait,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryOptions) Reset()         { *m = QueryOptions{} }
func (m *QueryOptions) String() string { return proto.CompactTextString(m) }
func (*QueryOptions) ProtoMessage()    {}
func (*QueryOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_search_a18b88daa5ffd15d, []int{0}
}
func (m *QueryOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryOptions.Unmarshal(m, b)
}
func (m *QueryOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryOptions.Marshal(b, m, deterministic)
}
func (dst *QueryOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryOptions.Merge(dst, src)
}
func (m *QueryOptions) XXX_Size() int {
	return xxx_messageInfo_QueryOptions.Size(m)
}
func (m *QueryOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryOptions.DiscardUnknown(m)
}

var xxx_messageInfo_QueryOptions proto.InternalMessageInfo

func (m *QueryOptions) GetLocal() bool {
	if m != nil {
		return m.Local
	}
	return false
}

func (m *QueryOptions) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *QueryOptions) GetWait() int32 {
	if m != nil {
		return m.Wait
	}
	return 0
}

type Query struct {
	Token                string        `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Type                 QueryType     `protobuf:"varint,2,opt,name=type,proto3,enum=QueryType" json:"type,omitempty"`
	Options              *QueryOptions `protobuf:"bytes,3,opt,name=options,proto3" json:"options,omitempty"`
	Payload              *any.Any      `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Query) Reset()         { *m = Query{} }
func (m *Query) String() string { return proto.CompactTextString(m) }
func (*Query) ProtoMessage()    {}
func (*Query) Descriptor() ([]byte, []int) {
	return fileDescriptor_search_a18b88daa5ffd15d, []int{1}
}
func (m *Query) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Query.Unmarshal(m, b)
}
func (m *Query) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Query.Marshal(b, m, deterministic)
}
func (dst *Query) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Query.Merge(dst, src)
}
func (m *Query) XXX_Size() int {
	return xxx_messageInfo_Query.Size(m)
}
func (m *Query) XXX_DiscardUnknown() {
	xxx_messageInfo_Query.DiscardUnknown(m)
}

var xxx_messageInfo_Query proto.InternalMessageInfo

func (m *Query) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *Query) GetType() QueryType {
	if m != nil {
		return m.Type
	}
	return QueryType_BACKUPS
}

func (m *Query) GetOptions() *QueryOptions {
	if m != nil {
		return m.Options
	}
	return nil
}

func (m *Query) GetPayload() *any.Any {
	if m != nil {
		return m.Payload
	}
	return nil
}

type PubSubQuery struct {
	Id                   string                   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type                 QueryType                `protobuf:"varint,2,opt,name=type,proto3,enum=QueryType" json:"type,omitempty"`
	Payload              *any.Any                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	ResponseType         PubSubQuery_ResponseType `protobuf:"varint,4,opt,name=responseType,proto3,enum=PubSubQuery_ResponseType" json:"responseType,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *PubSubQuery) Reset()         { *m = PubSubQuery{} }
func (m *PubSubQuery) String() string { return proto.CompactTextString(m) }
func (*PubSubQuery) ProtoMessage()    {}
func (*PubSubQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_search_a18b88daa5ffd15d, []int{2}
}
func (m *PubSubQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PubSubQuery.Unmarshal(m, b)
}
func (m *PubSubQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PubSubQuery.Marshal(b, m, deterministic)
}
func (dst *PubSubQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PubSubQuery.Merge(dst, src)
}
func (m *PubSubQuery) XXX_Size() int {
	return xxx_messageInfo_PubSubQuery.Size(m)
}
func (m *PubSubQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_PubSubQuery.DiscardUnknown(m)
}

var xxx_messageInfo_PubSubQuery proto.InternalMessageInfo

func (m *PubSubQuery) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PubSubQuery) GetType() QueryType {
	if m != nil {
		return m.Type
	}
	return QueryType_BACKUPS
}

func (m *PubSubQuery) GetPayload() *any.Any {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *PubSubQuery) GetResponseType() PubSubQuery_ResponseType {
	if m != nil {
		return m.ResponseType
	}
	return PubSubQuery_P2P
}

type QueryResult struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Date                 *timestamp.Timestamp `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	Local                bool                 `protobuf:"varint,3,opt,name=local,proto3" json:"local,omitempty"`
	Value                *any.Any             `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *QueryResult) Reset()         { *m = QueryResult{} }
func (m *QueryResult) String() string { return proto.CompactTextString(m) }
func (*QueryResult) ProtoMessage()    {}
func (*QueryResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_search_a18b88daa5ffd15d, []int{3}
}
func (m *QueryResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryResult.Unmarshal(m, b)
}
func (m *QueryResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryResult.Marshal(b, m, deterministic)
}
func (dst *QueryResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryResult.Merge(dst, src)
}
func (m *QueryResult) XXX_Size() int {
	return xxx_messageInfo_QueryResult.Size(m)
}
func (m *QueryResult) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryResult.DiscardUnknown(m)
}

var xxx_messageInfo_QueryResult proto.InternalMessageInfo

func (m *QueryResult) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *QueryResult) GetDate() *timestamp.Timestamp {
	if m != nil {
		return m.Date
	}
	return nil
}

func (m *QueryResult) GetLocal() bool {
	if m != nil {
		return m.Local
	}
	return false
}

func (m *QueryResult) GetValue() *any.Any {
	if m != nil {
		return m.Value
	}
	return nil
}

type QueryResults struct {
	Type                 QueryType      `protobuf:"varint,1,opt,name=type,proto3,enum=QueryType" json:"type,omitempty"`
	Items                []*QueryResult `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *QueryResults) Reset()         { *m = QueryResults{} }
func (m *QueryResults) String() string { return proto.CompactTextString(m) }
func (*QueryResults) ProtoMessage()    {}
func (*QueryResults) Descriptor() ([]byte, []int) {
	return fileDescriptor_search_a18b88daa5ffd15d, []int{4}
}
func (m *QueryResults) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryResults.Unmarshal(m, b)
}
func (m *QueryResults) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryResults.Marshal(b, m, deterministic)
}
func (dst *QueryResults) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryResults.Merge(dst, src)
}
func (m *QueryResults) XXX_Size() int {
	return xxx_messageInfo_QueryResults.Size(m)
}
func (m *QueryResults) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryResults.DiscardUnknown(m)
}

var xxx_messageInfo_QueryResults proto.InternalMessageInfo

func (m *QueryResults) GetType() QueryType {
	if m != nil {
		return m.Type
	}
	return QueryType_BACKUPS
}

func (m *QueryResults) GetItems() []*QueryResult {
	if m != nil {
		return m.Items
	}
	return nil
}

type PubSubQueryResults struct {
	Id                   string        `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Results              *QueryResults `protobuf:"bytes,2,opt,name=results,proto3" json:"results,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *PubSubQueryResults) Reset()         { *m = PubSubQueryResults{} }
func (m *PubSubQueryResults) String() string { return proto.CompactTextString(m) }
func (*PubSubQueryResults) ProtoMessage()    {}
func (*PubSubQueryResults) Descriptor() ([]byte, []int) {
	return fileDescriptor_search_a18b88daa5ffd15d, []int{5}
}
func (m *PubSubQueryResults) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PubSubQueryResults.Unmarshal(m, b)
}
func (m *PubSubQueryResults) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PubSubQueryResults.Marshal(b, m, deterministic)
}
func (dst *PubSubQueryResults) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PubSubQueryResults.Merge(dst, src)
}
func (m *PubSubQueryResults) XXX_Size() int {
	return xxx_messageInfo_PubSubQueryResults.Size(m)
}
func (m *PubSubQueryResults) XXX_DiscardUnknown() {
	xxx_messageInfo_PubSubQueryResults.DiscardUnknown(m)
}

var xxx_messageInfo_PubSubQueryResults proto.InternalMessageInfo

func (m *PubSubQueryResults) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PubSubQueryResults) GetResults() *QueryResults {
	if m != nil {
		return m.Results
	}
	return nil
}

type ContactQuery struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Address              string   `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Username             string   `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ContactQuery) Reset()         { *m = ContactQuery{} }
func (m *ContactQuery) String() string { return proto.CompactTextString(m) }
func (*ContactQuery) ProtoMessage()    {}
func (*ContactQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_search_a18b88daa5ffd15d, []int{6}
}
func (m *ContactQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContactQuery.Unmarshal(m, b)
}
func (m *ContactQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContactQuery.Marshal(b, m, deterministic)
}
func (dst *ContactQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContactQuery.Merge(dst, src)
}
func (m *ContactQuery) XXX_Size() int {
	return xxx_messageInfo_ContactQuery.Size(m)
}
func (m *ContactQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_ContactQuery.DiscardUnknown(m)
}

var xxx_messageInfo_ContactQuery proto.InternalMessageInfo

func (m *ContactQuery) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ContactQuery) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *ContactQuery) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type BackupQuery struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BackupQuery) Reset()         { *m = BackupQuery{} }
func (m *BackupQuery) String() string { return proto.CompactTextString(m) }
func (*BackupQuery) ProtoMessage()    {}
func (*BackupQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_search_a18b88daa5ffd15d, []int{7}
}
func (m *BackupQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BackupQuery.Unmarshal(m, b)
}
func (m *BackupQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BackupQuery.Marshal(b, m, deterministic)
}
func (dst *BackupQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BackupQuery.Merge(dst, src)
}
func (m *BackupQuery) XXX_Size() int {
	return xxx_messageInfo_BackupQuery.Size(m)
}
func (m *BackupQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_BackupQuery.DiscardUnknown(m)
}

var xxx_messageInfo_BackupQuery proto.InternalMessageInfo

func (m *BackupQuery) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func init() {
	proto.RegisterType((*QueryOptions)(nil), "QueryOptions")
	proto.RegisterType((*Query)(nil), "Query")
	proto.RegisterType((*PubSubQuery)(nil), "PubSubQuery")
	proto.RegisterType((*QueryResult)(nil), "QueryResult")
	proto.RegisterType((*QueryResults)(nil), "QueryResults")
	proto.RegisterType((*PubSubQueryResults)(nil), "PubSubQueryResults")
	proto.RegisterType((*ContactQuery)(nil), "ContactQuery")
	proto.RegisterType((*BackupQuery)(nil), "BackupQuery")
	proto.RegisterEnum("QueryType", QueryType_name, QueryType_value)
	proto.RegisterEnum("PubSubQuery_ResponseType", PubSubQuery_ResponseType_name, PubSubQuery_ResponseType_value)
}

func init() { proto.RegisterFile("search.proto", fileDescriptor_search_a18b88daa5ffd15d) }

var fileDescriptor_search_a18b88daa5ffd15d = []byte{
	// 489 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0xbd, 0x6e, 0xdb, 0x30,
	0x18, 0x0c, 0xfd, 0x13, 0xc5, 0x9f, 0x14, 0xc3, 0x20, 0x32, 0x28, 0x1e, 0x5a, 0x83, 0x05, 0x6a,
	0x23, 0x03, 0x03, 0xa8, 0x73, 0x07, 0xdb, 0x63, 0xd1, 0xc4, 0xa5, 0xe5, 0xa5, 0x1b, 0x65, 0xb1,
	0xa9, 0x10, 0x49, 0x14, 0x44, 0xaa, 0x85, 0x9e, 0xa2, 0x5b, 0xdf, 0xab, 0x6f, 0x54, 0x84, 0xb4,
	0x5c, 0x26, 0xe9, 0xdf, 0xa6, 0x8f, 0x77, 0x3a, 0xde, 0x1d, 0x3f, 0x08, 0x94, 0xe0, 0xf5, 0xfe,
	0x33, 0xad, 0x6a, 0xa9, 0xe5, 0xf4, 0xf2, 0x4e, 0xca, 0xbb, 0x5c, 0x5c, 0x9b, 0x29, 0x69, 0x3e,
	0x5d, 0xf3, 0xb2, 0x3d, 0x40, 0x2f, 0x9f, 0x42, 0x3a, 0x2b, 0x84, 0xd2, 0xbc, 0xa8, 0x2c, 0x81,
	0xdc, 0x40, 0xf0, 0xa1, 0x11, 0x75, 0x7b, 0x5b, 0xe9, 0x4c, 0x96, 0x0a, 0x5f, 0xc0, 0x30, 0x97,
	0x7b, 0x9e, 0x87, 0x68, 0x86, 0x16, 0x67, 0xcc, 0x0e, 0xe6, 0x34, 0x2b, 0x32, 0x1d, 0xf6, 0x66,
	0x68, 0x31, 0x64, 0x76, 0xc0, 0x18, 0x06, 0x5f, 0x79, 0xa6, 0xc3, 0xbe, 0x39, 0x34, 0xdf, 0xe4,
	0x3b, 0x82, 0xa1, 0x11, 0x7c, 0xf8, 0x47, 0xcb, 0x7b, 0x51, 0x1a, 0xa5, 0x11, 0xb3, 0x03, 0x7e,
	0x01, 0x03, 0xdd, 0x56, 0xc2, 0x08, 0x8d, 0x23, 0xa0, 0x86, 0x1b, 0xb7, 0x95, 0x60, 0xe6, 0x1c,
	0xcf, 0xc1, 0x93, 0xd6, 0x8a, 0x91, 0xf5, 0xa3, 0x73, 0xea, 0xfa, 0x63, 0x1d, 0x8a, 0x29, 0x78,
	0x15, 0x6f, 0x73, 0xc9, 0xd3, 0x70, 0x60, 0x88, 0x17, 0xd4, 0x66, 0xa5, 0x5d, 0x56, 0xba, 0x2c,
	0x5b, 0xd6, 0x91, 0xc8, 0x0f, 0x04, 0xfe, 0xa6, 0x49, 0xb6, 0x4d, 0x62, 0xed, 0x8d, 0xa1, 0x97,
	0xa5, 0x07, 0x6f, 0xbd, 0x2c, 0xfd, 0xa7, 0x31, 0xe7, 0xbe, 0xfe, 0x7f, 0xdc, 0x87, 0xdf, 0x42,
	0x50, 0x0b, 0x55, 0xc9, 0x52, 0x89, 0x07, 0x15, 0x63, 0x72, 0x1c, 0x5d, 0x52, 0xc7, 0x03, 0x65,
	0x0e, 0x81, 0x3d, 0xa2, 0x93, 0x57, 0x10, 0xb8, 0x28, 0xf6, 0xa0, 0xbf, 0x89, 0x36, 0x93, 0x13,
	0x0c, 0x70, 0xba, 0xd9, 0xad, 0xb6, 0xbb, 0xd5, 0x04, 0x91, 0x6f, 0x08, 0x7c, 0xa3, 0xc4, 0x84,
	0x6a, 0x72, 0xfd, 0x2c, 0x13, 0x85, 0x41, 0xca, 0xb5, 0xcd, 0xe4, 0x47, 0xd3, 0x67, 0x86, 0xe3,
	0x6e, 0x19, 0x98, 0xe1, 0xfd, 0x7a, 0xfc, 0xbe, 0xfb, 0xf8, 0x57, 0x30, 0xfc, 0xc2, 0xf3, 0x46,
	0xfc, 0xb5, 0x67, 0x4b, 0x21, 0xec, 0xb0, 0x4e, 0xd6, 0x90, 0x3a, 0xb6, 0x8a, 0xfe, 0xd0, 0x2a,
	0x81, 0x61, 0xa6, 0x45, 0xa1, 0xc2, 0xde, 0xac, 0xbf, 0xf0, 0xa3, 0x80, 0x3a, 0x7f, 0x33, 0x0b,
	0x91, 0xf7, 0x80, 0x9d, 0xd2, 0x3a, 0xe5, 0xa7, 0x59, 0xe7, 0xe0, 0xd5, 0x16, 0x3a, 0xc4, 0x3d,
	0x77, 0xb5, 0x14, 0xeb, 0x50, 0x12, 0x43, 0xb0, 0x96, 0xa5, 0xe6, 0x7b, 0xfd, 0xfb, 0x45, 0x08,
	0xc1, 0xe3, 0x69, 0x5a, 0x0b, 0x65, 0x85, 0x46, 0xac, 0x1b, 0xf1, 0x14, 0xce, 0x1a, 0x25, 0xea,
	0x92, 0x17, 0xc2, 0x34, 0x34, 0x62, 0xc7, 0x99, 0xcc, 0xc1, 0x5f, 0xf1, 0xfd, 0x7d, 0x53, 0x59,
	0x51, 0x47, 0x04, 0x3d, 0x12, 0xb9, 0x7a, 0x0d, 0xa3, 0x63, 0x09, 0xd8, 0x07, 0x6f, 0xb5, 0x5c,
	0xbf, 0xdb, 0x6d, 0xb6, 0x93, 0x13, 0x1c, 0xc0, 0xd9, 0xfa, 0xf6, 0x26, 0x5e, 0xae, 0xe3, 0xed,
	0x04, 0xad, 0x06, 0x1f, 0x7b, 0x55, 0x92, 0x9c, 0x9a, 0x92, 0xdf, 0xfc, 0x0c, 0x00, 0x00, 0xff,
	0xff, 0x31, 0xeb, 0xfc, 0xa8, 0xf1, 0x03, 0x00, 0x00,
}
