// Code generated by protoc-gen-go. DO NOT EDIT.
// source: thread_blocks.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ThreadData_Type int32

const (
	ThreadData_PHOTO ThreadData_Type = 0
	ThreadData_TEXT  ThreadData_Type = 1
)

var ThreadData_Type_name = map[int32]string{
	0: "PHOTO",
	1: "TEXT",
}
var ThreadData_Type_value = map[string]int32{
	"PHOTO": 0,
	"TEXT":  1,
}

func (x ThreadData_Type) String() string {
	return proto.EnumName(ThreadData_Type_name, int32(x))
}
func (ThreadData_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_thread_blocks_e5bffd30384cec35, []int{6, 0}
}

type ThreadAnnotation_Type int32

const (
	ThreadAnnotation_COMMENT ThreadAnnotation_Type = 0
	ThreadAnnotation_LIKE    ThreadAnnotation_Type = 1
)

var ThreadAnnotation_Type_name = map[int32]string{
	0: "COMMENT",
	1: "LIKE",
}
var ThreadAnnotation_Type_value = map[string]int32{
	"COMMENT": 0,
	"LIKE":    1,
}

func (x ThreadAnnotation_Type) String() string {
	return proto.EnumName(ThreadAnnotation_Type_name, int32(x))
}
func (ThreadAnnotation_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_thread_blocks_e5bffd30384cec35, []int{7, 0}
}

type ThreadBlockHeader struct {
	Date                 *timestamp.Timestamp `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	Parents              []string             `protobuf:"bytes,2,rep,name=parents,proto3" json:"parents,omitempty"`
	ThreadPk             []byte               `protobuf:"bytes,3,opt,name=threadPk,proto3" json:"threadPk,omitempty"`
	AuthorPk             []byte               `protobuf:"bytes,4,opt,name=authorPk,proto3" json:"authorPk,omitempty"`
	AuthorUnCipher       []byte               `protobuf:"bytes,5,opt,name=authorUnCipher,proto3" json:"authorUnCipher,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ThreadBlockHeader) Reset()         { *m = ThreadBlockHeader{} }
func (m *ThreadBlockHeader) String() string { return proto.CompactTextString(m) }
func (*ThreadBlockHeader) ProtoMessage()    {}
func (*ThreadBlockHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_thread_blocks_e5bffd30384cec35, []int{0}
}
func (m *ThreadBlockHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ThreadBlockHeader.Unmarshal(m, b)
}
func (m *ThreadBlockHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ThreadBlockHeader.Marshal(b, m, deterministic)
}
func (dst *ThreadBlockHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ThreadBlockHeader.Merge(dst, src)
}
func (m *ThreadBlockHeader) XXX_Size() int {
	return xxx_messageInfo_ThreadBlockHeader.Size(m)
}
func (m *ThreadBlockHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_ThreadBlockHeader.DiscardUnknown(m)
}

var xxx_messageInfo_ThreadBlockHeader proto.InternalMessageInfo

func (m *ThreadBlockHeader) GetDate() *timestamp.Timestamp {
	if m != nil {
		return m.Date
	}
	return nil
}

func (m *ThreadBlockHeader) GetParents() []string {
	if m != nil {
		return m.Parents
	}
	return nil
}

func (m *ThreadBlockHeader) GetThreadPk() []byte {
	if m != nil {
		return m.ThreadPk
	}
	return nil
}

func (m *ThreadBlockHeader) GetAuthorPk() []byte {
	if m != nil {
		return m.AuthorPk
	}
	return nil
}

func (m *ThreadBlockHeader) GetAuthorUnCipher() []byte {
	if m != nil {
		return m.AuthorUnCipher
	}
	return nil
}

type SignedThreadBlock struct {
	Block                []byte   `protobuf:"bytes,1,opt,name=block,proto3" json:"block,omitempty"`
	ThreadSig            []byte   `protobuf:"bytes,2,opt,name=threadSig,proto3" json:"threadSig,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignedThreadBlock) Reset()         { *m = SignedThreadBlock{} }
func (m *SignedThreadBlock) String() string { return proto.CompactTextString(m) }
func (*SignedThreadBlock) ProtoMessage()    {}
func (*SignedThreadBlock) Descriptor() ([]byte, []int) {
	return fileDescriptor_thread_blocks_e5bffd30384cec35, []int{1}
}
func (m *SignedThreadBlock) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignedThreadBlock.Unmarshal(m, b)
}
func (m *SignedThreadBlock) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignedThreadBlock.Marshal(b, m, deterministic)
}
func (dst *SignedThreadBlock) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignedThreadBlock.Merge(dst, src)
}
func (m *SignedThreadBlock) XXX_Size() int {
	return xxx_messageInfo_SignedThreadBlock.Size(m)
}
func (m *SignedThreadBlock) XXX_DiscardUnknown() {
	xxx_messageInfo_SignedThreadBlock.DiscardUnknown(m)
}

var xxx_messageInfo_SignedThreadBlock proto.InternalMessageInfo

func (m *SignedThreadBlock) GetBlock() []byte {
	if m != nil {
		return m.Block
	}
	return nil
}

func (m *SignedThreadBlock) GetThreadSig() []byte {
	if m != nil {
		return m.ThreadSig
	}
	return nil
}

type ThreadInvite struct {
	Header               *ThreadBlockHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	SkCipher             []byte             `protobuf:"bytes,2,opt,name=skCipher,proto3" json:"skCipher,omitempty"`
	SuggestedName        string             `protobuf:"bytes,3,opt,name=suggestedName,proto3" json:"suggestedName,omitempty"`
	InviteeId            string             `protobuf:"bytes,4,opt,name=inviteeId,proto3" json:"inviteeId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ThreadInvite) Reset()         { *m = ThreadInvite{} }
func (m *ThreadInvite) String() string { return proto.CompactTextString(m) }
func (*ThreadInvite) ProtoMessage()    {}
func (*ThreadInvite) Descriptor() ([]byte, []int) {
	return fileDescriptor_thread_blocks_e5bffd30384cec35, []int{2}
}
func (m *ThreadInvite) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ThreadInvite.Unmarshal(m, b)
}
func (m *ThreadInvite) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ThreadInvite.Marshal(b, m, deterministic)
}
func (dst *ThreadInvite) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ThreadInvite.Merge(dst, src)
}
func (m *ThreadInvite) XXX_Size() int {
	return xxx_messageInfo_ThreadInvite.Size(m)
}
func (m *ThreadInvite) XXX_DiscardUnknown() {
	xxx_messageInfo_ThreadInvite.DiscardUnknown(m)
}

var xxx_messageInfo_ThreadInvite proto.InternalMessageInfo

func (m *ThreadInvite) GetHeader() *ThreadBlockHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *ThreadInvite) GetSkCipher() []byte {
	if m != nil {
		return m.SkCipher
	}
	return nil
}

func (m *ThreadInvite) GetSuggestedName() string {
	if m != nil {
		return m.SuggestedName
	}
	return ""
}

func (m *ThreadInvite) GetInviteeId() string {
	if m != nil {
		return m.InviteeId
	}
	return ""
}

type ThreadExternalInvite struct {
	Header               *ThreadBlockHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	SkCipher             []byte             `protobuf:"bytes,2,opt,name=skCipher,proto3" json:"skCipher,omitempty"`
	SuggestedName        string             `protobuf:"bytes,3,opt,name=suggestedName,proto3" json:"suggestedName,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ThreadExternalInvite) Reset()         { *m = ThreadExternalInvite{} }
func (m *ThreadExternalInvite) String() string { return proto.CompactTextString(m) }
func (*ThreadExternalInvite) ProtoMessage()    {}
func (*ThreadExternalInvite) Descriptor() ([]byte, []int) {
	return fileDescriptor_thread_blocks_e5bffd30384cec35, []int{3}
}
func (m *ThreadExternalInvite) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ThreadExternalInvite.Unmarshal(m, b)
}
func (m *ThreadExternalInvite) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ThreadExternalInvite.Marshal(b, m, deterministic)
}
func (dst *ThreadExternalInvite) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ThreadExternalInvite.Merge(dst, src)
}
func (m *ThreadExternalInvite) XXX_Size() int {
	return xxx_messageInfo_ThreadExternalInvite.Size(m)
}
func (m *ThreadExternalInvite) XXX_DiscardUnknown() {
	xxx_messageInfo_ThreadExternalInvite.DiscardUnknown(m)
}

var xxx_messageInfo_ThreadExternalInvite proto.InternalMessageInfo

func (m *ThreadExternalInvite) GetHeader() *ThreadBlockHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *ThreadExternalInvite) GetSkCipher() []byte {
	if m != nil {
		return m.SkCipher
	}
	return nil
}

func (m *ThreadExternalInvite) GetSuggestedName() string {
	if m != nil {
		return m.SuggestedName
	}
	return ""
}

type ThreadJoin struct {
	Header               *ThreadBlockHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	InviterPk            []byte             `protobuf:"bytes,2,opt,name=inviterPk,proto3" json:"inviterPk,omitempty"`
	BlockId              string             `protobuf:"bytes,3,opt,name=blockId,proto3" json:"blockId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ThreadJoin) Reset()         { *m = ThreadJoin{} }
func (m *ThreadJoin) String() string { return proto.CompactTextString(m) }
func (*ThreadJoin) ProtoMessage()    {}
func (*ThreadJoin) Descriptor() ([]byte, []int) {
	return fileDescriptor_thread_blocks_e5bffd30384cec35, []int{4}
}
func (m *ThreadJoin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ThreadJoin.Unmarshal(m, b)
}
func (m *ThreadJoin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ThreadJoin.Marshal(b, m, deterministic)
}
func (dst *ThreadJoin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ThreadJoin.Merge(dst, src)
}
func (m *ThreadJoin) XXX_Size() int {
	return xxx_messageInfo_ThreadJoin.Size(m)
}
func (m *ThreadJoin) XXX_DiscardUnknown() {
	xxx_messageInfo_ThreadJoin.DiscardUnknown(m)
}

var xxx_messageInfo_ThreadJoin proto.InternalMessageInfo

func (m *ThreadJoin) GetHeader() *ThreadBlockHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *ThreadJoin) GetInviterPk() []byte {
	if m != nil {
		return m.InviterPk
	}
	return nil
}

func (m *ThreadJoin) GetBlockId() string {
	if m != nil {
		return m.BlockId
	}
	return ""
}

type ThreadLeave struct {
	Header               *ThreadBlockHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ThreadLeave) Reset()         { *m = ThreadLeave{} }
func (m *ThreadLeave) String() string { return proto.CompactTextString(m) }
func (*ThreadLeave) ProtoMessage()    {}
func (*ThreadLeave) Descriptor() ([]byte, []int) {
	return fileDescriptor_thread_blocks_e5bffd30384cec35, []int{5}
}
func (m *ThreadLeave) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ThreadLeave.Unmarshal(m, b)
}
func (m *ThreadLeave) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ThreadLeave.Marshal(b, m, deterministic)
}
func (dst *ThreadLeave) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ThreadLeave.Merge(dst, src)
}
func (m *ThreadLeave) XXX_Size() int {
	return xxx_messageInfo_ThreadLeave.Size(m)
}
func (m *ThreadLeave) XXX_DiscardUnknown() {
	xxx_messageInfo_ThreadLeave.DiscardUnknown(m)
}

var xxx_messageInfo_ThreadLeave proto.InternalMessageInfo

func (m *ThreadLeave) GetHeader() *ThreadBlockHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type ThreadData struct {
	Header               *ThreadBlockHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Type                 ThreadData_Type    `protobuf:"varint,2,opt,name=type,proto3,enum=ThreadData_Type" json:"type,omitempty"`
	DataId               string             `protobuf:"bytes,3,opt,name=dataId,proto3" json:"dataId,omitempty"`
	KeyCipher            []byte             `protobuf:"bytes,4,opt,name=keyCipher,proto3" json:"keyCipher,omitempty"`
	CaptionCipher        []byte             `protobuf:"bytes,5,opt,name=captionCipher,proto3" json:"captionCipher,omitempty"`
	UsernameCipher       []byte             `protobuf:"bytes,6,opt,name=usernameCipher,proto3" json:"usernameCipher,omitempty"` // Deprecated: Do not use.
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ThreadData) Reset()         { *m = ThreadData{} }
func (m *ThreadData) String() string { return proto.CompactTextString(m) }
func (*ThreadData) ProtoMessage()    {}
func (*ThreadData) Descriptor() ([]byte, []int) {
	return fileDescriptor_thread_blocks_e5bffd30384cec35, []int{6}
}
func (m *ThreadData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ThreadData.Unmarshal(m, b)
}
func (m *ThreadData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ThreadData.Marshal(b, m, deterministic)
}
func (dst *ThreadData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ThreadData.Merge(dst, src)
}
func (m *ThreadData) XXX_Size() int {
	return xxx_messageInfo_ThreadData.Size(m)
}
func (m *ThreadData) XXX_DiscardUnknown() {
	xxx_messageInfo_ThreadData.DiscardUnknown(m)
}

var xxx_messageInfo_ThreadData proto.InternalMessageInfo

func (m *ThreadData) GetHeader() *ThreadBlockHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *ThreadData) GetType() ThreadData_Type {
	if m != nil {
		return m.Type
	}
	return ThreadData_PHOTO
}

func (m *ThreadData) GetDataId() string {
	if m != nil {
		return m.DataId
	}
	return ""
}

func (m *ThreadData) GetKeyCipher() []byte {
	if m != nil {
		return m.KeyCipher
	}
	return nil
}

func (m *ThreadData) GetCaptionCipher() []byte {
	if m != nil {
		return m.CaptionCipher
	}
	return nil
}

// Deprecated: Do not use.
func (m *ThreadData) GetUsernameCipher() []byte {
	if m != nil {
		return m.UsernameCipher
	}
	return nil
}

type ThreadAnnotation struct {
	Header               *ThreadBlockHeader    `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Type                 ThreadAnnotation_Type `protobuf:"varint,2,opt,name=type,proto3,enum=ThreadAnnotation_Type" json:"type,omitempty"`
	CaptionCipher        []byte                `protobuf:"bytes,5,opt,name=captionCipher,proto3" json:"captionCipher,omitempty"`
	UsernameCipher       []byte                `protobuf:"bytes,6,opt,name=usernameCipher,proto3" json:"usernameCipher,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ThreadAnnotation) Reset()         { *m = ThreadAnnotation{} }
func (m *ThreadAnnotation) String() string { return proto.CompactTextString(m) }
func (*ThreadAnnotation) ProtoMessage()    {}
func (*ThreadAnnotation) Descriptor() ([]byte, []int) {
	return fileDescriptor_thread_blocks_e5bffd30384cec35, []int{7}
}
func (m *ThreadAnnotation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ThreadAnnotation.Unmarshal(m, b)
}
func (m *ThreadAnnotation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ThreadAnnotation.Marshal(b, m, deterministic)
}
func (dst *ThreadAnnotation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ThreadAnnotation.Merge(dst, src)
}
func (m *ThreadAnnotation) XXX_Size() int {
	return xxx_messageInfo_ThreadAnnotation.Size(m)
}
func (m *ThreadAnnotation) XXX_DiscardUnknown() {
	xxx_messageInfo_ThreadAnnotation.DiscardUnknown(m)
}

var xxx_messageInfo_ThreadAnnotation proto.InternalMessageInfo

func (m *ThreadAnnotation) GetHeader() *ThreadBlockHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *ThreadAnnotation) GetType() ThreadAnnotation_Type {
	if m != nil {
		return m.Type
	}
	return ThreadAnnotation_COMMENT
}

func (m *ThreadAnnotation) GetCaptionCipher() []byte {
	if m != nil {
		return m.CaptionCipher
	}
	return nil
}

func (m *ThreadAnnotation) GetUsernameCipher() []byte {
	if m != nil {
		return m.UsernameCipher
	}
	return nil
}

type ThreadIgnore struct {
	Header               *ThreadBlockHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	DataId               string             `protobuf:"bytes,2,opt,name=dataId,proto3" json:"dataId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ThreadIgnore) Reset()         { *m = ThreadIgnore{} }
func (m *ThreadIgnore) String() string { return proto.CompactTextString(m) }
func (*ThreadIgnore) ProtoMessage()    {}
func (*ThreadIgnore) Descriptor() ([]byte, []int) {
	return fileDescriptor_thread_blocks_e5bffd30384cec35, []int{8}
}
func (m *ThreadIgnore) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ThreadIgnore.Unmarshal(m, b)
}
func (m *ThreadIgnore) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ThreadIgnore.Marshal(b, m, deterministic)
}
func (dst *ThreadIgnore) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ThreadIgnore.Merge(dst, src)
}
func (m *ThreadIgnore) XXX_Size() int {
	return xxx_messageInfo_ThreadIgnore.Size(m)
}
func (m *ThreadIgnore) XXX_DiscardUnknown() {
	xxx_messageInfo_ThreadIgnore.DiscardUnknown(m)
}

var xxx_messageInfo_ThreadIgnore proto.InternalMessageInfo

func (m *ThreadIgnore) GetHeader() *ThreadBlockHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *ThreadIgnore) GetDataId() string {
	if m != nil {
		return m.DataId
	}
	return ""
}

type ThreadMerge struct {
	Parents              []string `protobuf:"bytes,2,rep,name=parents,proto3" json:"parents,omitempty"`
	ThreadPk             []byte   `protobuf:"bytes,3,opt,name=threadPk,proto3" json:"threadPk,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ThreadMerge) Reset()         { *m = ThreadMerge{} }
func (m *ThreadMerge) String() string { return proto.CompactTextString(m) }
func (*ThreadMerge) ProtoMessage()    {}
func (*ThreadMerge) Descriptor() ([]byte, []int) {
	return fileDescriptor_thread_blocks_e5bffd30384cec35, []int{9}
}
func (m *ThreadMerge) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ThreadMerge.Unmarshal(m, b)
}
func (m *ThreadMerge) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ThreadMerge.Marshal(b, m, deterministic)
}
func (dst *ThreadMerge) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ThreadMerge.Merge(dst, src)
}
func (m *ThreadMerge) XXX_Size() int {
	return xxx_messageInfo_ThreadMerge.Size(m)
}
func (m *ThreadMerge) XXX_DiscardUnknown() {
	xxx_messageInfo_ThreadMerge.DiscardUnknown(m)
}

var xxx_messageInfo_ThreadMerge proto.InternalMessageInfo

func (m *ThreadMerge) GetParents() []string {
	if m != nil {
		return m.Parents
	}
	return nil
}

func (m *ThreadMerge) GetThreadPk() []byte {
	if m != nil {
		return m.ThreadPk
	}
	return nil
}

func init() {
	proto.RegisterType((*ThreadBlockHeader)(nil), "ThreadBlockHeader")
	proto.RegisterType((*SignedThreadBlock)(nil), "SignedThreadBlock")
	proto.RegisterType((*ThreadInvite)(nil), "ThreadInvite")
	proto.RegisterType((*ThreadExternalInvite)(nil), "ThreadExternalInvite")
	proto.RegisterType((*ThreadJoin)(nil), "ThreadJoin")
	proto.RegisterType((*ThreadLeave)(nil), "ThreadLeave")
	proto.RegisterType((*ThreadData)(nil), "ThreadData")
	proto.RegisterType((*ThreadAnnotation)(nil), "ThreadAnnotation")
	proto.RegisterType((*ThreadIgnore)(nil), "ThreadIgnore")
	proto.RegisterType((*ThreadMerge)(nil), "ThreadMerge")
	proto.RegisterEnum("ThreadData_Type", ThreadData_Type_name, ThreadData_Type_value)
	proto.RegisterEnum("ThreadAnnotation_Type", ThreadAnnotation_Type_name, ThreadAnnotation_Type_value)
}

func init() { proto.RegisterFile("thread_blocks.proto", fileDescriptor_thread_blocks_e5bffd30384cec35) }

var fileDescriptor_thread_blocks_e5bffd30384cec35 = []byte{
	// 554 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x54, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0xc6, 0xae, 0x93, 0x36, 0x93, 0x10, 0xa5, 0x4b, 0x55, 0x59, 0x01, 0x44, 0xb4, 0xaa, 0xaa,
	0x28, 0x07, 0x57, 0x2a, 0x27, 0x8e, 0x24, 0x44, 0x34, 0xd0, 0x34, 0x91, 0x6b, 0x24, 0xc4, 0x05,
	0x6d, 0xea, 0xc1, 0xb1, 0x92, 0x78, 0x2d, 0x7b, 0x53, 0x91, 0x33, 0x3c, 0x05, 0xef, 0xc2, 0x73,
	0xf0, 0x3a, 0x68, 0x77, 0x6d, 0xe7, 0xa7, 0x1c, 0x08, 0x17, 0x6e, 0x9e, 0x1f, 0x7f, 0xf3, 0x7d,
	0xdf, 0x8c, 0x0d, 0x4f, 0xc4, 0x34, 0x41, 0xe6, 0x7f, 0x9e, 0xcc, 0xf9, 0xdd, 0x2c, 0x75, 0xe2,
	0x84, 0x0b, 0xde, 0x7c, 0x11, 0x70, 0x1e, 0xcc, 0xf1, 0x42, 0x45, 0x93, 0xe5, 0x97, 0x0b, 0x11,
	0x2e, 0x30, 0x15, 0x6c, 0x11, 0xeb, 0x06, 0xfa, 0xd3, 0x80, 0x63, 0x4f, 0xbd, 0xd8, 0x95, 0xef,
	0x5d, 0x21, 0xf3, 0x31, 0x21, 0x0e, 0x58, 0x3e, 0x13, 0x68, 0x1b, 0x2d, 0xa3, 0x5d, 0xbd, 0x6c,
	0x3a, 0x1a, 0xc5, 0xc9, 0x51, 0x1c, 0x2f, 0x47, 0x71, 0x55, 0x1f, 0xb1, 0xe1, 0x30, 0x66, 0x09,
	0x46, 0x22, 0xb5, 0xcd, 0xd6, 0x41, 0xbb, 0xe2, 0xe6, 0x21, 0x69, 0xc2, 0x91, 0xe6, 0x35, 0x9e,
	0xd9, 0x07, 0x2d, 0xa3, 0x5d, 0x73, 0x8b, 0x58, 0xd6, 0xd8, 0x52, 0x4c, 0x79, 0x32, 0x9e, 0xd9,
	0x96, 0xae, 0xe5, 0x31, 0x39, 0x87, 0xba, 0x7e, 0xfe, 0x10, 0xf5, 0xc2, 0x78, 0x8a, 0x89, 0x5d,
	0x52, 0x1d, 0x3b, 0x59, 0xfa, 0x16, 0x8e, 0x6f, 0xc3, 0x20, 0x42, 0x7f, 0x43, 0x04, 0x39, 0x81,
	0x92, 0x72, 0x41, 0xf1, 0xaf, 0xb9, 0x3a, 0x20, 0xcf, 0xa0, 0xa2, 0x47, 0xdf, 0x86, 0x81, 0x6d,
	0xaa, 0xca, 0x3a, 0x41, 0x7f, 0x18, 0x50, 0xd3, 0x18, 0x83, 0xe8, 0x3e, 0x14, 0x48, 0x3a, 0x50,
	0x9e, 0x2a, 0x37, 0x32, 0x17, 0x88, 0xf3, 0xc0, 0x27, 0x37, 0xeb, 0x90, 0x4a, 0xd2, 0x59, 0xc6,
	0x53, 0x23, 0x17, 0x31, 0x39, 0x83, 0xc7, 0xe9, 0x32, 0x08, 0x30, 0x15, 0xe8, 0xdf, 0xb0, 0x05,
	0x2a, 0x1b, 0x2a, 0xee, 0x76, 0x52, 0x92, 0x0b, 0xd5, 0x5c, 0x1c, 0xf8, 0xca, 0x8c, 0x8a, 0xbb,
	0x4e, 0xd0, 0xef, 0x06, 0x9c, 0xe8, 0xe9, 0xfd, 0xaf, 0x02, 0x93, 0x88, 0xcd, 0xff, 0x07, 0x49,
	0x1a, 0x03, 0x68, 0xf8, 0x77, 0x3c, 0x8c, 0xf6, 0x9a, 0x5d, 0xc8, 0x93, 0xbb, 0xce, 0xbc, 0x2f,
	0x12, 0xf2, 0x7c, 0xd4, 0x8a, 0x06, 0x7e, 0x36, 0x37, 0x0f, 0xe9, 0x2b, 0xa8, 0x6a, 0xd0, 0x6b,
	0x64, 0xf7, 0x7b, 0xc9, 0xa5, 0xdf, 0xcc, 0x9c, 0xed, 0x1b, 0x26, 0xd8, 0x5e, 0x6c, 0xcf, 0xc0,
	0x12, 0xab, 0x18, 0x15, 0xd1, 0xfa, 0x65, 0xc3, 0x59, 0xc3, 0x38, 0xde, 0x2a, 0x46, 0x57, 0x55,
	0xc9, 0x29, 0x94, 0x7d, 0x26, 0x58, 0x41, 0x3a, 0x8b, 0xa4, 0xd6, 0x19, 0xae, 0x32, 0xa3, 0xf5,
	0x5d, 0xaf, 0x13, 0xd2, 0xe9, 0x3b, 0x16, 0x8b, 0x90, 0x6f, 0xdf, 0xf5, 0x76, 0x92, 0x74, 0xa0,
	0xbe, 0x4c, 0xe5, 0xa2, 0x17, 0x98, 0xb5, 0x95, 0x65, 0x5b, 0xd7, 0xb4, 0x0d, 0x77, 0xa7, 0x42,
	0x9f, 0x82, 0x25, 0x59, 0x91, 0x0a, 0x94, 0xc6, 0x57, 0x23, 0x6f, 0xd4, 0x78, 0x44, 0x8e, 0xc0,
	0xf2, 0xfa, 0x1f, 0xbd, 0x86, 0x41, 0x7f, 0x19, 0xd0, 0xd0, 0xf4, 0x5f, 0x47, 0x11, 0x17, 0x4c,
	0xce, 0xd8, 0xcb, 0x8b, 0xce, 0x96, 0x17, 0xa7, 0xce, 0x2e, 0xd8, 0xa6, 0x23, 0x7f, 0xa7, 0xed,
	0xfc, 0xcf, 0xda, 0x1e, 0xe8, 0x7a, 0x9e, 0xe9, 0xaa, 0xc2, 0x61, 0x6f, 0x34, 0x1c, 0xf6, 0x6f,
	0x3c, 0xad, 0xec, 0x7a, 0xf0, 0xbe, 0xdf, 0x30, 0xa8, 0x5b, 0x7c, 0xaf, 0x41, 0xc4, 0x93, 0xfd,
	0x3e, 0x85, 0xf5, 0xea, 0xcc, 0xcd, 0xd5, 0xd1, 0x5e, 0x7e, 0x6e, 0x43, 0x4c, 0x82, 0x7f, 0xfc,
	0xad, 0x75, 0xad, 0x4f, 0x66, 0x3c, 0x99, 0x94, 0xd5, 0xcf, 0xf2, 0xe5, 0xef, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x87, 0xa2, 0xa7, 0xde, 0x97, 0x05, 0x00, 0x00,
}
