// Code generated by protoc-gen-go. DO NOT EDIT.
// source: thread.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import any "github.com/golang/protobuf/ptypes/any"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// for wire transport
type ThreadEnvelope struct {
	Thread               string   `protobuf:"bytes,1,opt,name=thread,proto3" json:"thread,omitempty"`
	Hash                 string   `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	Ciphertext           []byte   `protobuf:"bytes,3,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ThreadEnvelope) Reset()         { *m = ThreadEnvelope{} }
func (m *ThreadEnvelope) String() string { return proto.CompactTextString(m) }
func (*ThreadEnvelope) ProtoMessage()    {}
func (*ThreadEnvelope) Descriptor() ([]byte, []int) {
	return fileDescriptor_thread_fea751881932b6df, []int{0}
}
func (m *ThreadEnvelope) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ThreadEnvelope.Unmarshal(m, b)
}
func (m *ThreadEnvelope) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ThreadEnvelope.Marshal(b, m, deterministic)
}
func (dst *ThreadEnvelope) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ThreadEnvelope.Merge(dst, src)
}
func (m *ThreadEnvelope) XXX_Size() int {
	return xxx_messageInfo_ThreadEnvelope.Size(m)
}
func (m *ThreadEnvelope) XXX_DiscardUnknown() {
	xxx_messageInfo_ThreadEnvelope.DiscardUnknown(m)
}

var xxx_messageInfo_ThreadEnvelope proto.InternalMessageInfo

func (m *ThreadEnvelope) GetThread() string {
	if m != nil {
		return m.Thread
	}
	return ""
}

func (m *ThreadEnvelope) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *ThreadEnvelope) GetCiphertext() []byte {
	if m != nil {
		return m.Ciphertext
	}
	return nil
}

type ThreadBlock struct {
	Header               *ThreadBlockHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Type                 Block_BlockType    `protobuf:"varint,2,opt,name=type,proto3,enum=Block_BlockType" json:"type,omitempty"`
	Payload              *any.Any           `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ThreadBlock) Reset()         { *m = ThreadBlock{} }
func (m *ThreadBlock) String() string { return proto.CompactTextString(m) }
func (*ThreadBlock) ProtoMessage()    {}
func (*ThreadBlock) Descriptor() ([]byte, []int) {
	return fileDescriptor_thread_fea751881932b6df, []int{1}
}
func (m *ThreadBlock) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ThreadBlock.Unmarshal(m, b)
}
func (m *ThreadBlock) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ThreadBlock.Marshal(b, m, deterministic)
}
func (dst *ThreadBlock) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ThreadBlock.Merge(dst, src)
}
func (m *ThreadBlock) XXX_Size() int {
	return xxx_messageInfo_ThreadBlock.Size(m)
}
func (m *ThreadBlock) XXX_DiscardUnknown() {
	xxx_messageInfo_ThreadBlock.DiscardUnknown(m)
}

var xxx_messageInfo_ThreadBlock proto.InternalMessageInfo

func (m *ThreadBlock) GetHeader() *ThreadBlockHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *ThreadBlock) GetType() Block_BlockType {
	if m != nil {
		return m.Type
	}
	return Block_MERGE
}

func (m *ThreadBlock) GetPayload() *any.Any {
	if m != nil {
		return m.Payload
	}
	return nil
}

type ThreadBlockHeader struct {
	Date                 *timestamp.Timestamp `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	Parents              []string             `protobuf:"bytes,2,rep,name=parents,proto3" json:"parents,omitempty"`
	Author               string               `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	Address              string               `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ThreadBlockHeader) Reset()         { *m = ThreadBlockHeader{} }
func (m *ThreadBlockHeader) String() string { return proto.CompactTextString(m) }
func (*ThreadBlockHeader) ProtoMessage()    {}
func (*ThreadBlockHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_thread_fea751881932b6df, []int{2}
}
func (m *ThreadBlockHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ThreadBlockHeader.Unmarshal(m, b)
}
func (m *ThreadBlockHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ThreadBlockHeader.Marshal(b, m, deterministic)
}
func (dst *ThreadBlockHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ThreadBlockHeader.Merge(dst, src)
}
func (m *ThreadBlockHeader) XXX_Size() int {
	return xxx_messageInfo_ThreadBlockHeader.Size(m)
}
func (m *ThreadBlockHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_ThreadBlockHeader.DiscardUnknown(m)
}

var xxx_messageInfo_ThreadBlockHeader proto.InternalMessageInfo

func (m *ThreadBlockHeader) GetDate() *timestamp.Timestamp {
	if m != nil {
		return m.Date
	}
	return nil
}

func (m *ThreadBlockHeader) GetParents() []string {
	if m != nil {
		return m.Parents
	}
	return nil
}

func (m *ThreadBlockHeader) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *ThreadBlockHeader) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type ThreadInvite struct {
	Inviter              *Contact `protobuf:"bytes,1,opt,name=inviter,proto3" json:"inviter,omitempty"`
	Thread               *Thread  `protobuf:"bytes,2,opt,name=thread,proto3" json:"thread,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ThreadInvite) Reset()         { *m = ThreadInvite{} }
func (m *ThreadInvite) String() string { return proto.CompactTextString(m) }
func (*ThreadInvite) ProtoMessage()    {}
func (*ThreadInvite) Descriptor() ([]byte, []int) {
	return fileDescriptor_thread_fea751881932b6df, []int{3}
}
func (m *ThreadInvite) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ThreadInvite.Unmarshal(m, b)
}
func (m *ThreadInvite) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ThreadInvite.Marshal(b, m, deterministic)
}
func (dst *ThreadInvite) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ThreadInvite.Merge(dst, src)
}
func (m *ThreadInvite) XXX_Size() int {
	return xxx_messageInfo_ThreadInvite.Size(m)
}
func (m *ThreadInvite) XXX_DiscardUnknown() {
	xxx_messageInfo_ThreadInvite.DiscardUnknown(m)
}

var xxx_messageInfo_ThreadInvite proto.InternalMessageInfo

func (m *ThreadInvite) GetInviter() *Contact {
	if m != nil {
		return m.Inviter
	}
	return nil
}

func (m *ThreadInvite) GetThread() *Thread {
	if m != nil {
		return m.Thread
	}
	return nil
}

type ThreadIgnore struct {
	Target               string   `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ThreadIgnore) Reset()         { *m = ThreadIgnore{} }
func (m *ThreadIgnore) String() string { return proto.CompactTextString(m) }
func (*ThreadIgnore) ProtoMessage()    {}
func (*ThreadIgnore) Descriptor() ([]byte, []int) {
	return fileDescriptor_thread_fea751881932b6df, []int{4}
}
func (m *ThreadIgnore) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ThreadIgnore.Unmarshal(m, b)
}
func (m *ThreadIgnore) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ThreadIgnore.Marshal(b, m, deterministic)
}
func (dst *ThreadIgnore) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ThreadIgnore.Merge(dst, src)
}
func (m *ThreadIgnore) XXX_Size() int {
	return xxx_messageInfo_ThreadIgnore.Size(m)
}
func (m *ThreadIgnore) XXX_DiscardUnknown() {
	xxx_messageInfo_ThreadIgnore.DiscardUnknown(m)
}

var xxx_messageInfo_ThreadIgnore proto.InternalMessageInfo

func (m *ThreadIgnore) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

type ThreadFlag struct {
	Target               string   `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ThreadFlag) Reset()         { *m = ThreadFlag{} }
func (m *ThreadFlag) String() string { return proto.CompactTextString(m) }
func (*ThreadFlag) ProtoMessage()    {}
func (*ThreadFlag) Descriptor() ([]byte, []int) {
	return fileDescriptor_thread_fea751881932b6df, []int{5}
}
func (m *ThreadFlag) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ThreadFlag.Unmarshal(m, b)
}
func (m *ThreadFlag) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ThreadFlag.Marshal(b, m, deterministic)
}
func (dst *ThreadFlag) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ThreadFlag.Merge(dst, src)
}
func (m *ThreadFlag) XXX_Size() int {
	return xxx_messageInfo_ThreadFlag.Size(m)
}
func (m *ThreadFlag) XXX_DiscardUnknown() {
	xxx_messageInfo_ThreadFlag.DiscardUnknown(m)
}

var xxx_messageInfo_ThreadFlag proto.InternalMessageInfo

func (m *ThreadFlag) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

type ThreadJoin struct {
	Inviter              string   `protobuf:"bytes,1,opt,name=inviter,proto3" json:"inviter,omitempty"`
	Contact              *Contact `protobuf:"bytes,2,opt,name=contact,proto3" json:"contact,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ThreadJoin) Reset()         { *m = ThreadJoin{} }
func (m *ThreadJoin) String() string { return proto.CompactTextString(m) }
func (*ThreadJoin) ProtoMessage()    {}
func (*ThreadJoin) Descriptor() ([]byte, []int) {
	return fileDescriptor_thread_fea751881932b6df, []int{6}
}
func (m *ThreadJoin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ThreadJoin.Unmarshal(m, b)
}
func (m *ThreadJoin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ThreadJoin.Marshal(b, m, deterministic)
}
func (dst *ThreadJoin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ThreadJoin.Merge(dst, src)
}
func (m *ThreadJoin) XXX_Size() int {
	return xxx_messageInfo_ThreadJoin.Size(m)
}
func (m *ThreadJoin) XXX_DiscardUnknown() {
	xxx_messageInfo_ThreadJoin.DiscardUnknown(m)
}

var xxx_messageInfo_ThreadJoin proto.InternalMessageInfo

func (m *ThreadJoin) GetInviter() string {
	if m != nil {
		return m.Inviter
	}
	return ""
}

func (m *ThreadJoin) GetContact() *Contact {
	if m != nil {
		return m.Contact
	}
	return nil
}

type ThreadAnnounce struct {
	Contact              *Contact `protobuf:"bytes,1,opt,name=contact,proto3" json:"contact,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ThreadAnnounce) Reset()         { *m = ThreadAnnounce{} }
func (m *ThreadAnnounce) String() string { return proto.CompactTextString(m) }
func (*ThreadAnnounce) ProtoMessage()    {}
func (*ThreadAnnounce) Descriptor() ([]byte, []int) {
	return fileDescriptor_thread_fea751881932b6df, []int{7}
}
func (m *ThreadAnnounce) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ThreadAnnounce.Unmarshal(m, b)
}
func (m *ThreadAnnounce) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ThreadAnnounce.Marshal(b, m, deterministic)
}
func (dst *ThreadAnnounce) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ThreadAnnounce.Merge(dst, src)
}
func (m *ThreadAnnounce) XXX_Size() int {
	return xxx_messageInfo_ThreadAnnounce.Size(m)
}
func (m *ThreadAnnounce) XXX_DiscardUnknown() {
	xxx_messageInfo_ThreadAnnounce.DiscardUnknown(m)
}

var xxx_messageInfo_ThreadAnnounce proto.InternalMessageInfo

func (m *ThreadAnnounce) GetContact() *Contact {
	if m != nil {
		return m.Contact
	}
	return nil
}

type ThreadMessage struct {
	Body                 string   `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ThreadMessage) Reset()         { *m = ThreadMessage{} }
func (m *ThreadMessage) String() string { return proto.CompactTextString(m) }
func (*ThreadMessage) ProtoMessage()    {}
func (*ThreadMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_thread_fea751881932b6df, []int{8}
}
func (m *ThreadMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ThreadMessage.Unmarshal(m, b)
}
func (m *ThreadMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ThreadMessage.Marshal(b, m, deterministic)
}
func (dst *ThreadMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ThreadMessage.Merge(dst, src)
}
func (m *ThreadMessage) XXX_Size() int {
	return xxx_messageInfo_ThreadMessage.Size(m)
}
func (m *ThreadMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ThreadMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ThreadMessage proto.InternalMessageInfo

func (m *ThreadMessage) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

type ThreadFiles struct {
	Target               string            `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	Body                 string            `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	Keys                 map[string]string `protobuf:"bytes,3,rep,name=keys,proto3" json:"keys,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ThreadFiles) Reset()         { *m = ThreadFiles{} }
func (m *ThreadFiles) String() string { return proto.CompactTextString(m) }
func (*ThreadFiles) ProtoMessage()    {}
func (*ThreadFiles) Descriptor() ([]byte, []int) {
	return fileDescriptor_thread_fea751881932b6df, []int{9}
}
func (m *ThreadFiles) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ThreadFiles.Unmarshal(m, b)
}
func (m *ThreadFiles) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ThreadFiles.Marshal(b, m, deterministic)
}
func (dst *ThreadFiles) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ThreadFiles.Merge(dst, src)
}
func (m *ThreadFiles) XXX_Size() int {
	return xxx_messageInfo_ThreadFiles.Size(m)
}
func (m *ThreadFiles) XXX_DiscardUnknown() {
	xxx_messageInfo_ThreadFiles.DiscardUnknown(m)
}

var xxx_messageInfo_ThreadFiles proto.InternalMessageInfo

func (m *ThreadFiles) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

func (m *ThreadFiles) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *ThreadFiles) GetKeys() map[string]string {
	if m != nil {
		return m.Keys
	}
	return nil
}

type ThreadComment struct {
	Target               string   `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	Body                 string   `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ThreadComment) Reset()         { *m = ThreadComment{} }
func (m *ThreadComment) String() string { return proto.CompactTextString(m) }
func (*ThreadComment) ProtoMessage()    {}
func (*ThreadComment) Descriptor() ([]byte, []int) {
	return fileDescriptor_thread_fea751881932b6df, []int{10}
}
func (m *ThreadComment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ThreadComment.Unmarshal(m, b)
}
func (m *ThreadComment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ThreadComment.Marshal(b, m, deterministic)
}
func (dst *ThreadComment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ThreadComment.Merge(dst, src)
}
func (m *ThreadComment) XXX_Size() int {
	return xxx_messageInfo_ThreadComment.Size(m)
}
func (m *ThreadComment) XXX_DiscardUnknown() {
	xxx_messageInfo_ThreadComment.DiscardUnknown(m)
}

var xxx_messageInfo_ThreadComment proto.InternalMessageInfo

func (m *ThreadComment) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

func (m *ThreadComment) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

type ThreadLike struct {
	Target               string   `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ThreadLike) Reset()         { *m = ThreadLike{} }
func (m *ThreadLike) String() string { return proto.CompactTextString(m) }
func (*ThreadLike) ProtoMessage()    {}
func (*ThreadLike) Descriptor() ([]byte, []int) {
	return fileDescriptor_thread_fea751881932b6df, []int{11}
}
func (m *ThreadLike) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ThreadLike.Unmarshal(m, b)
}
func (m *ThreadLike) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ThreadLike.Marshal(b, m, deterministic)
}
func (dst *ThreadLike) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ThreadLike.Merge(dst, src)
}
func (m *ThreadLike) XXX_Size() int {
	return xxx_messageInfo_ThreadLike.Size(m)
}
func (m *ThreadLike) XXX_DiscardUnknown() {
	xxx_messageInfo_ThreadLike.DiscardUnknown(m)
}

var xxx_messageInfo_ThreadLike proto.InternalMessageInfo

func (m *ThreadLike) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

func init() {
	proto.RegisterType((*ThreadEnvelope)(nil), "ThreadEnvelope")
	proto.RegisterType((*ThreadBlock)(nil), "ThreadBlock")
	proto.RegisterType((*ThreadBlockHeader)(nil), "ThreadBlockHeader")
	proto.RegisterType((*ThreadInvite)(nil), "ThreadInvite")
	proto.RegisterType((*ThreadIgnore)(nil), "ThreadIgnore")
	proto.RegisterType((*ThreadFlag)(nil), "ThreadFlag")
	proto.RegisterType((*ThreadJoin)(nil), "ThreadJoin")
	proto.RegisterType((*ThreadAnnounce)(nil), "ThreadAnnounce")
	proto.RegisterType((*ThreadMessage)(nil), "ThreadMessage")
	proto.RegisterType((*ThreadFiles)(nil), "ThreadFiles")
	proto.RegisterMapType((map[string]string)(nil), "ThreadFiles.KeysEntry")
	proto.RegisterType((*ThreadComment)(nil), "ThreadComment")
	proto.RegisterType((*ThreadLike)(nil), "ThreadLike")
}

func init() { proto.RegisterFile("thread.proto", fileDescriptor_thread_fea751881932b6df) }

var fileDescriptor_thread_fea751881932b6df = []byte{
	// 518 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0x95, 0x1d, 0x93, 0x90, 0x49, 0xa8, 0xca, 0xaa, 0xaa, 0x4c, 0x0e, 0x34, 0x32, 0x15, 0x8a,
	0x7a, 0xd8, 0x4a, 0x01, 0x09, 0x04, 0xa7, 0xb6, 0x6a, 0x05, 0x05, 0x2e, 0x26, 0x27, 0xc4, 0x65,
	0x13, 0x0f, 0xb6, 0x15, 0x67, 0xd7, 0xf2, 0x6e, 0x22, 0xfc, 0x2b, 0xf8, 0x07, 0xfc, 0x56, 0xe4,
	0xfd, 0x70, 0x2c, 0xaa, 0x1c, 0x7a, 0xb1, 0xf6, 0xf9, 0xbd, 0x99, 0x79, 0xf3, 0x01, 0x63, 0x95,
	0x55, 0xc8, 0x12, 0x5a, 0x56, 0x42, 0x89, 0xc9, 0x8b, 0x54, 0x88, 0xb4, 0xc0, 0x4b, 0x8d, 0x96,
	0xdb, 0x5f, 0x97, 0x8c, 0xd7, 0x96, 0x3a, 0xfb, 0x9f, 0x52, 0xf9, 0x06, 0xa5, 0x62, 0x9b, 0xd2,
	0x0a, 0x46, 0x1b, 0x91, 0x60, 0x61, 0x40, 0xf4, 0x13, 0x8e, 0x16, 0x3a, 0xf1, 0x2d, 0xdf, 0x61,
	0x21, 0x4a, 0x24, 0xa7, 0xd0, 0x37, 0xa5, 0x42, 0x6f, 0xea, 0xcd, 0x86, 0xb1, 0x45, 0x84, 0x40,
	0x90, 0x31, 0x99, 0x85, 0xbe, 0xfe, 0xab, 0xdf, 0xe4, 0x25, 0xc0, 0x2a, 0x2f, 0x33, 0xac, 0x14,
	0xfe, 0x56, 0x61, 0x6f, 0xea, 0xcd, 0xc6, 0x71, 0xe7, 0x4f, 0xf4, 0xc7, 0x83, 0x91, 0x49, 0x7f,
	0x5d, 0x88, 0xd5, 0x9a, 0x5c, 0x40, 0x3f, 0x43, 0x96, 0x60, 0xa5, 0x73, 0x8f, 0xe6, 0x84, 0x76,
	0xd8, 0x4f, 0x9a, 0x89, 0xad, 0x82, 0x9c, 0x43, 0xa0, 0xea, 0x12, 0x75, 0xbd, 0xa3, 0xf9, 0x31,
	0xd5, 0x1a, 0xf3, 0x5d, 0xd4, 0x25, 0xc6, 0x9a, 0x25, 0x14, 0x06, 0x25, 0xab, 0x0b, 0xc1, 0x12,
	0x5d, 0x7e, 0x34, 0x3f, 0xa1, 0xa6, 0x7f, 0xea, 0xfa, 0xa7, 0x57, 0xbc, 0x8e, 0x9d, 0xa8, 0x71,
	0xf4, 0xfc, 0x41, 0x4d, 0x42, 0x21, 0x48, 0x98, 0x42, 0xeb, 0x6a, 0xf2, 0x20, 0xc5, 0xc2, 0x8d,
	0x30, 0xd6, 0x3a, 0x12, 0x36, 0x55, 0x2b, 0xe4, 0x4a, 0x86, 0xfe, 0xb4, 0x37, 0x1b, 0xc6, 0x0e,
	0x36, 0xd3, 0x63, 0x5b, 0x95, 0x89, 0x4a, 0xdb, 0x19, 0xc6, 0x16, 0x35, 0x11, 0x2c, 0x49, 0x2a,
	0x94, 0x32, 0x0c, 0x34, 0xe1, 0x60, 0xf4, 0x1d, 0xc6, 0xc6, 0xd0, 0x67, 0xbe, 0xcb, 0x15, 0x92,
	0x08, 0x06, 0xb9, 0x7e, 0xb9, 0x21, 0x3d, 0xa5, 0x37, 0x82, 0x2b, 0xb6, 0x52, 0xb1, 0x23, 0xc8,
	0x59, 0xbb, 0x23, 0x5f, 0x4b, 0x06, 0x76, 0x8e, 0x6e, 0x59, 0xd1, 0xeb, 0x36, 0x69, 0xca, 0x45,
	0x65, 0x96, 0xca, 0xaa, 0x14, 0x55, 0xbb, 0x54, 0x8d, 0xa2, 0x73, 0x00, 0xa3, 0xbb, 0x2b, 0x58,
	0x7a, 0x50, 0x75, 0xef, 0x54, 0xf7, 0x22, 0xe7, 0x4d, 0x2b, 0x5d, 0x83, 0xc3, 0xbd, 0xad, 0x08,
	0x06, 0x2b, 0x63, 0xd5, 0xfa, 0xea, 0x58, 0xb7, 0x44, 0xf4, 0xd6, 0x1d, 0xdc, 0x15, 0xe7, 0x62,
	0xcb, 0x57, 0xd8, 0x8d, 0xf2, 0x0e, 0x45, 0xbd, 0x82, 0x67, 0x26, 0xea, 0x1b, 0x4a, 0xc9, 0x52,
	0x6c, 0xae, 0x71, 0x29, 0x92, 0xda, 0x3a, 0xd0, 0xef, 0xe8, 0x6f, 0x7b, 0x6d, 0x77, 0x79, 0x81,
	0xf2, 0x50, 0x3b, 0x6d, 0xac, 0xbf, 0x8f, 0x25, 0x17, 0x10, 0xac, 0xb1, 0x96, 0x61, 0x6f, 0xda,
	0x9b, 0x8d, 0xe6, 0xa7, 0xb4, 0x93, 0x87, 0x7e, 0xc1, 0x5a, 0xde, 0x72, 0x55, 0xd5, 0xb1, 0xd6,
	0x4c, 0xde, 0xc1, 0xb0, 0xfd, 0x45, 0x8e, 0xa1, 0xb7, 0x46, 0xe7, 0xa3, 0x79, 0x92, 0x13, 0x78,
	0xb2, 0x63, 0xc5, 0x16, 0x6d, 0x7e, 0x03, 0x3e, 0xf8, 0xef, 0xbd, 0xe8, 0xa3, 0xeb, 0xe2, 0x46,
	0x6c, 0x36, 0xc8, 0xd5, 0x63, 0x1c, 0xee, 0x57, 0xf5, 0x35, 0x5f, 0x1f, 0x5c, 0xe8, 0x75, 0xf0,
	0xc3, 0x2f, 0x97, 0xcb, 0xbe, 0xbe, 0xdc, 0x37, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0x8c, 0x8b,
	0x8e, 0x85, 0x35, 0x04, 0x00, 0x00,
}
