// Code generated by protoc-gen-go. DO NOT EDIT.
// source: thread.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import any "github.com/golang/protobuf/ptypes/any"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ThreadBlock_Type int32

const (
	ThreadBlock_MERGE    ThreadBlock_Type = 0
	ThreadBlock_IGNORE   ThreadBlock_Type = 1
	ThreadBlock_FLAG     ThreadBlock_Type = 2
	ThreadBlock_JOIN     ThreadBlock_Type = 3
	ThreadBlock_ANNOUNCE ThreadBlock_Type = 4
	ThreadBlock_LEAVE    ThreadBlock_Type = 5
	ThreadBlock_MESSAGE  ThreadBlock_Type = 6
	ThreadBlock_FILES    ThreadBlock_Type = 7
	ThreadBlock_COMMENT  ThreadBlock_Type = 8
	ThreadBlock_LIKE     ThreadBlock_Type = 9
	ThreadBlock_INVITE   ThreadBlock_Type = 50
)

var ThreadBlock_Type_name = map[int32]string{
	0:  "MERGE",
	1:  "IGNORE",
	2:  "FLAG",
	3:  "JOIN",
	4:  "ANNOUNCE",
	5:  "LEAVE",
	6:  "MESSAGE",
	7:  "FILES",
	8:  "COMMENT",
	9:  "LIKE",
	50: "INVITE",
}
var ThreadBlock_Type_value = map[string]int32{
	"MERGE":    0,
	"IGNORE":   1,
	"FLAG":     2,
	"JOIN":     3,
	"ANNOUNCE": 4,
	"LEAVE":    5,
	"MESSAGE":  6,
	"FILES":    7,
	"COMMENT":  8,
	"LIKE":     9,
	"INVITE":   50,
}

func (x ThreadBlock_Type) String() string {
	return proto.EnumName(ThreadBlock_Type_name, int32(x))
}
func (ThreadBlock_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_thread_d695b8acd230a8b4, []int{1, 0}
}

// for wire transport
type ThreadEnvelope struct {
	Thread               string   `protobuf:"bytes,1,opt,name=thread,proto3" json:"thread,omitempty"`
	Hash                 string   `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	Ciphertext           []byte   `protobuf:"bytes,3,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ThreadEnvelope) Reset()         { *m = ThreadEnvelope{} }
func (m *ThreadEnvelope) String() string { return proto.CompactTextString(m) }
func (*ThreadEnvelope) ProtoMessage()    {}
func (*ThreadEnvelope) Descriptor() ([]byte, []int) {
	return fileDescriptor_thread_d695b8acd230a8b4, []int{0}
}
func (m *ThreadEnvelope) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ThreadEnvelope.Unmarshal(m, b)
}
func (m *ThreadEnvelope) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ThreadEnvelope.Marshal(b, m, deterministic)
}
func (dst *ThreadEnvelope) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ThreadEnvelope.Merge(dst, src)
}
func (m *ThreadEnvelope) XXX_Size() int {
	return xxx_messageInfo_ThreadEnvelope.Size(m)
}
func (m *ThreadEnvelope) XXX_DiscardUnknown() {
	xxx_messageInfo_ThreadEnvelope.DiscardUnknown(m)
}

var xxx_messageInfo_ThreadEnvelope proto.InternalMessageInfo

func (m *ThreadEnvelope) GetThread() string {
	if m != nil {
		return m.Thread
	}
	return ""
}

func (m *ThreadEnvelope) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *ThreadEnvelope) GetCiphertext() []byte {
	if m != nil {
		return m.Ciphertext
	}
	return nil
}

type ThreadBlock struct {
	Header               *ThreadBlockHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Type                 ThreadBlock_Type   `protobuf:"varint,2,opt,name=type,proto3,enum=ThreadBlock_Type" json:"type,omitempty"`
	Payload              *any.Any           `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ThreadBlock) Reset()         { *m = ThreadBlock{} }
func (m *ThreadBlock) String() string { return proto.CompactTextString(m) }
func (*ThreadBlock) ProtoMessage()    {}
func (*ThreadBlock) Descriptor() ([]byte, []int) {
	return fileDescriptor_thread_d695b8acd230a8b4, []int{1}
}
func (m *ThreadBlock) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ThreadBlock.Unmarshal(m, b)
}
func (m *ThreadBlock) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ThreadBlock.Marshal(b, m, deterministic)
}
func (dst *ThreadBlock) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ThreadBlock.Merge(dst, src)
}
func (m *ThreadBlock) XXX_Size() int {
	return xxx_messageInfo_ThreadBlock.Size(m)
}
func (m *ThreadBlock) XXX_DiscardUnknown() {
	xxx_messageInfo_ThreadBlock.DiscardUnknown(m)
}

var xxx_messageInfo_ThreadBlock proto.InternalMessageInfo

func (m *ThreadBlock) GetHeader() *ThreadBlockHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *ThreadBlock) GetType() ThreadBlock_Type {
	if m != nil {
		return m.Type
	}
	return ThreadBlock_MERGE
}

func (m *ThreadBlock) GetPayload() *any.Any {
	if m != nil {
		return m.Payload
	}
	return nil
}

type ThreadBlockHeader struct {
	Date                 *timestamp.Timestamp `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	Parents              []string             `protobuf:"bytes,2,rep,name=parents,proto3" json:"parents,omitempty"`
	Author               string               `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	Address              string               `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ThreadBlockHeader) Reset()         { *m = ThreadBlockHeader{} }
func (m *ThreadBlockHeader) String() string { return proto.CompactTextString(m) }
func (*ThreadBlockHeader) ProtoMessage()    {}
func (*ThreadBlockHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_thread_d695b8acd230a8b4, []int{2}
}
func (m *ThreadBlockHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ThreadBlockHeader.Unmarshal(m, b)
}
func (m *ThreadBlockHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ThreadBlockHeader.Marshal(b, m, deterministic)
}
func (dst *ThreadBlockHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ThreadBlockHeader.Merge(dst, src)
}
func (m *ThreadBlockHeader) XXX_Size() int {
	return xxx_messageInfo_ThreadBlockHeader.Size(m)
}
func (m *ThreadBlockHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_ThreadBlockHeader.DiscardUnknown(m)
}

var xxx_messageInfo_ThreadBlockHeader proto.InternalMessageInfo

func (m *ThreadBlockHeader) GetDate() *timestamp.Timestamp {
	if m != nil {
		return m.Date
	}
	return nil
}

func (m *ThreadBlockHeader) GetParents() []string {
	if m != nil {
		return m.Parents
	}
	return nil
}

func (m *ThreadBlockHeader) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *ThreadBlockHeader) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type ThreadInvite struct {
	Sk                   []byte   `protobuf:"bytes,1,opt,name=sk,proto3" json:"sk,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Schema               string   `protobuf:"bytes,3,opt,name=schema,proto3" json:"schema,omitempty"`
	Initiator            string   `protobuf:"bytes,4,opt,name=initiator,proto3" json:"initiator,omitempty"`
	Contact              *Contact `protobuf:"bytes,5,opt,name=contact,proto3" json:"contact,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ThreadInvite) Reset()         { *m = ThreadInvite{} }
func (m *ThreadInvite) String() string { return proto.CompactTextString(m) }
func (*ThreadInvite) ProtoMessage()    {}
func (*ThreadInvite) Descriptor() ([]byte, []int) {
	return fileDescriptor_thread_d695b8acd230a8b4, []int{3}
}
func (m *ThreadInvite) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ThreadInvite.Unmarshal(m, b)
}
func (m *ThreadInvite) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ThreadInvite.Marshal(b, m, deterministic)
}
func (dst *ThreadInvite) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ThreadInvite.Merge(dst, src)
}
func (m *ThreadInvite) XXX_Size() int {
	return xxx_messageInfo_ThreadInvite.Size(m)
}
func (m *ThreadInvite) XXX_DiscardUnknown() {
	xxx_messageInfo_ThreadInvite.DiscardUnknown(m)
}

var xxx_messageInfo_ThreadInvite proto.InternalMessageInfo

func (m *ThreadInvite) GetSk() []byte {
	if m != nil {
		return m.Sk
	}
	return nil
}

func (m *ThreadInvite) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ThreadInvite) GetSchema() string {
	if m != nil {
		return m.Schema
	}
	return ""
}

func (m *ThreadInvite) GetInitiator() string {
	if m != nil {
		return m.Initiator
	}
	return ""
}

func (m *ThreadInvite) GetContact() *Contact {
	if m != nil {
		return m.Contact
	}
	return nil
}

type ThreadIgnore struct {
	Target               string   `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ThreadIgnore) Reset()         { *m = ThreadIgnore{} }
func (m *ThreadIgnore) String() string { return proto.CompactTextString(m) }
func (*ThreadIgnore) ProtoMessage()    {}
func (*ThreadIgnore) Descriptor() ([]byte, []int) {
	return fileDescriptor_thread_d695b8acd230a8b4, []int{4}
}
func (m *ThreadIgnore) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ThreadIgnore.Unmarshal(m, b)
}
func (m *ThreadIgnore) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ThreadIgnore.Marshal(b, m, deterministic)
}
func (dst *ThreadIgnore) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ThreadIgnore.Merge(dst, src)
}
func (m *ThreadIgnore) XXX_Size() int {
	return xxx_messageInfo_ThreadIgnore.Size(m)
}
func (m *ThreadIgnore) XXX_DiscardUnknown() {
	xxx_messageInfo_ThreadIgnore.DiscardUnknown(m)
}

var xxx_messageInfo_ThreadIgnore proto.InternalMessageInfo

func (m *ThreadIgnore) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

type ThreadFlag struct {
	Target               string   `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ThreadFlag) Reset()         { *m = ThreadFlag{} }
func (m *ThreadFlag) String() string { return proto.CompactTextString(m) }
func (*ThreadFlag) ProtoMessage()    {}
func (*ThreadFlag) Descriptor() ([]byte, []int) {
	return fileDescriptor_thread_d695b8acd230a8b4, []int{5}
}
func (m *ThreadFlag) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ThreadFlag.Unmarshal(m, b)
}
func (m *ThreadFlag) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ThreadFlag.Marshal(b, m, deterministic)
}
func (dst *ThreadFlag) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ThreadFlag.Merge(dst, src)
}
func (m *ThreadFlag) XXX_Size() int {
	return xxx_messageInfo_ThreadFlag.Size(m)
}
func (m *ThreadFlag) XXX_DiscardUnknown() {
	xxx_messageInfo_ThreadFlag.DiscardUnknown(m)
}

var xxx_messageInfo_ThreadFlag proto.InternalMessageInfo

func (m *ThreadFlag) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

type ThreadJoin struct {
	Inviter              string   `protobuf:"bytes,1,opt,name=inviter,proto3" json:"inviter,omitempty"`
	Contact              *Contact `protobuf:"bytes,2,opt,name=contact,proto3" json:"contact,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ThreadJoin) Reset()         { *m = ThreadJoin{} }
func (m *ThreadJoin) String() string { return proto.CompactTextString(m) }
func (*ThreadJoin) ProtoMessage()    {}
func (*ThreadJoin) Descriptor() ([]byte, []int) {
	return fileDescriptor_thread_d695b8acd230a8b4, []int{6}
}
func (m *ThreadJoin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ThreadJoin.Unmarshal(m, b)
}
func (m *ThreadJoin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ThreadJoin.Marshal(b, m, deterministic)
}
func (dst *ThreadJoin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ThreadJoin.Merge(dst, src)
}
func (m *ThreadJoin) XXX_Size() int {
	return xxx_messageInfo_ThreadJoin.Size(m)
}
func (m *ThreadJoin) XXX_DiscardUnknown() {
	xxx_messageInfo_ThreadJoin.DiscardUnknown(m)
}

var xxx_messageInfo_ThreadJoin proto.InternalMessageInfo

func (m *ThreadJoin) GetInviter() string {
	if m != nil {
		return m.Inviter
	}
	return ""
}

func (m *ThreadJoin) GetContact() *Contact {
	if m != nil {
		return m.Contact
	}
	return nil
}

type ThreadAnnounce struct {
	Contact              *Contact `protobuf:"bytes,1,opt,name=contact,proto3" json:"contact,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ThreadAnnounce) Reset()         { *m = ThreadAnnounce{} }
func (m *ThreadAnnounce) String() string { return proto.CompactTextString(m) }
func (*ThreadAnnounce) ProtoMessage()    {}
func (*ThreadAnnounce) Descriptor() ([]byte, []int) {
	return fileDescriptor_thread_d695b8acd230a8b4, []int{7}
}
func (m *ThreadAnnounce) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ThreadAnnounce.Unmarshal(m, b)
}
func (m *ThreadAnnounce) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ThreadAnnounce.Marshal(b, m, deterministic)
}
func (dst *ThreadAnnounce) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ThreadAnnounce.Merge(dst, src)
}
func (m *ThreadAnnounce) XXX_Size() int {
	return xxx_messageInfo_ThreadAnnounce.Size(m)
}
func (m *ThreadAnnounce) XXX_DiscardUnknown() {
	xxx_messageInfo_ThreadAnnounce.DiscardUnknown(m)
}

var xxx_messageInfo_ThreadAnnounce proto.InternalMessageInfo

func (m *ThreadAnnounce) GetContact() *Contact {
	if m != nil {
		return m.Contact
	}
	return nil
}

type ThreadMessage struct {
	Body                 string   `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ThreadMessage) Reset()         { *m = ThreadMessage{} }
func (m *ThreadMessage) String() string { return proto.CompactTextString(m) }
func (*ThreadMessage) ProtoMessage()    {}
func (*ThreadMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_thread_d695b8acd230a8b4, []int{8}
}
func (m *ThreadMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ThreadMessage.Unmarshal(m, b)
}
func (m *ThreadMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ThreadMessage.Marshal(b, m, deterministic)
}
func (dst *ThreadMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ThreadMessage.Merge(dst, src)
}
func (m *ThreadMessage) XXX_Size() int {
	return xxx_messageInfo_ThreadMessage.Size(m)
}
func (m *ThreadMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ThreadMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ThreadMessage proto.InternalMessageInfo

func (m *ThreadMessage) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

type ThreadFiles struct {
	Target               string            `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	Body                 string            `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	Keys                 map[string]string `protobuf:"bytes,3,rep,name=keys,proto3" json:"keys,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ThreadFiles) Reset()         { *m = ThreadFiles{} }
func (m *ThreadFiles) String() string { return proto.CompactTextString(m) }
func (*ThreadFiles) ProtoMessage()    {}
func (*ThreadFiles) Descriptor() ([]byte, []int) {
	return fileDescriptor_thread_d695b8acd230a8b4, []int{9}
}
func (m *ThreadFiles) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ThreadFiles.Unmarshal(m, b)
}
func (m *ThreadFiles) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ThreadFiles.Marshal(b, m, deterministic)
}
func (dst *ThreadFiles) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ThreadFiles.Merge(dst, src)
}
func (m *ThreadFiles) XXX_Size() int {
	return xxx_messageInfo_ThreadFiles.Size(m)
}
func (m *ThreadFiles) XXX_DiscardUnknown() {
	xxx_messageInfo_ThreadFiles.DiscardUnknown(m)
}

var xxx_messageInfo_ThreadFiles proto.InternalMessageInfo

func (m *ThreadFiles) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

func (m *ThreadFiles) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *ThreadFiles) GetKeys() map[string]string {
	if m != nil {
		return m.Keys
	}
	return nil
}

type ThreadComment struct {
	Target               string   `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	Body                 string   `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ThreadComment) Reset()         { *m = ThreadComment{} }
func (m *ThreadComment) String() string { return proto.CompactTextString(m) }
func (*ThreadComment) ProtoMessage()    {}
func (*ThreadComment) Descriptor() ([]byte, []int) {
	return fileDescriptor_thread_d695b8acd230a8b4, []int{10}
}
func (m *ThreadComment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ThreadComment.Unmarshal(m, b)
}
func (m *ThreadComment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ThreadComment.Marshal(b, m, deterministic)
}
func (dst *ThreadComment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ThreadComment.Merge(dst, src)
}
func (m *ThreadComment) XXX_Size() int {
	return xxx_messageInfo_ThreadComment.Size(m)
}
func (m *ThreadComment) XXX_DiscardUnknown() {
	xxx_messageInfo_ThreadComment.DiscardUnknown(m)
}

var xxx_messageInfo_ThreadComment proto.InternalMessageInfo

func (m *ThreadComment) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

func (m *ThreadComment) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

type ThreadLike struct {
	Target               string   `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ThreadLike) Reset()         { *m = ThreadLike{} }
func (m *ThreadLike) String() string { return proto.CompactTextString(m) }
func (*ThreadLike) ProtoMessage()    {}
func (*ThreadLike) Descriptor() ([]byte, []int) {
	return fileDescriptor_thread_d695b8acd230a8b4, []int{11}
}
func (m *ThreadLike) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ThreadLike.Unmarshal(m, b)
}
func (m *ThreadLike) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ThreadLike.Marshal(b, m, deterministic)
}
func (dst *ThreadLike) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ThreadLike.Merge(dst, src)
}
func (m *ThreadLike) XXX_Size() int {
	return xxx_messageInfo_ThreadLike.Size(m)
}
func (m *ThreadLike) XXX_DiscardUnknown() {
	xxx_messageInfo_ThreadLike.DiscardUnknown(m)
}

var xxx_messageInfo_ThreadLike proto.InternalMessageInfo

func (m *ThreadLike) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

func init() {
	proto.RegisterType((*ThreadEnvelope)(nil), "ThreadEnvelope")
	proto.RegisterType((*ThreadBlock)(nil), "ThreadBlock")
	proto.RegisterType((*ThreadBlockHeader)(nil), "ThreadBlockHeader")
	proto.RegisterType((*ThreadInvite)(nil), "ThreadInvite")
	proto.RegisterType((*ThreadIgnore)(nil), "ThreadIgnore")
	proto.RegisterType((*ThreadFlag)(nil), "ThreadFlag")
	proto.RegisterType((*ThreadJoin)(nil), "ThreadJoin")
	proto.RegisterType((*ThreadAnnounce)(nil), "ThreadAnnounce")
	proto.RegisterType((*ThreadMessage)(nil), "ThreadMessage")
	proto.RegisterType((*ThreadFiles)(nil), "ThreadFiles")
	proto.RegisterMapType((map[string]string)(nil), "ThreadFiles.KeysEntry")
	proto.RegisterType((*ThreadComment)(nil), "ThreadComment")
	proto.RegisterType((*ThreadLike)(nil), "ThreadLike")
	proto.RegisterEnum("ThreadBlock_Type", ThreadBlock_Type_name, ThreadBlock_Type_value)
}

func init() { proto.RegisterFile("thread.proto", fileDescriptor_thread_d695b8acd230a8b4) }

var fileDescriptor_thread_d695b8acd230a8b4 = []byte{
	// 657 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0x4b, 0x6f, 0xd3, 0x40,
	0x10, 0xc6, 0x8e, 0xf3, 0x9a, 0x84, 0xca, 0x5d, 0x55, 0x95, 0xa9, 0x10, 0x44, 0xe6, 0xa1, 0xa8,
	0x07, 0x57, 0x0a, 0x48, 0x20, 0x38, 0xa5, 0xd1, 0x26, 0xa4, 0xcd, 0x43, 0x72, 0x43, 0x0f, 0x88,
	0xcb, 0x26, 0x5e, 0x12, 0x2b, 0xce, 0xae, 0x65, 0x6f, 0x2a, 0xfc, 0x03, 0xb8, 0x21, 0x71, 0xe5,
	0xc4, 0x6f, 0x45, 0xbb, 0xf6, 0xa6, 0x11, 0x55, 0x0e, 0xdc, 0xf6, 0x9b, 0xf9, 0x66, 0xe6, 0x9b,
	0xc7, 0x42, 0x53, 0xac, 0x12, 0x4a, 0x02, 0x2f, 0x4e, 0xb8, 0xe0, 0x67, 0x4f, 0x96, 0x9c, 0x2f,
	0x23, 0x7a, 0xa1, 0xd0, 0x7c, 0xfb, 0xed, 0x82, 0xb0, 0xac, 0x70, 0x3d, 0xff, 0xd7, 0x25, 0xc2,
	0x0d, 0x4d, 0x05, 0xd9, 0xc4, 0x05, 0xa1, 0xb1, 0xe1, 0x01, 0x8d, 0x72, 0xe0, 0x7e, 0x85, 0xa3,
	0x99, 0x4a, 0x8c, 0xd9, 0x1d, 0x8d, 0x78, 0x4c, 0xd1, 0x29, 0x54, 0xf2, 0x52, 0x8e, 0xd1, 0x32,
	0xda, 0x75, 0xbf, 0x40, 0x08, 0x81, 0xb5, 0x22, 0xe9, 0xca, 0x31, 0x95, 0x55, 0xbd, 0xd1, 0x33,
	0x80, 0x45, 0x18, 0xaf, 0x68, 0x22, 0xe8, 0x77, 0xe1, 0x94, 0x5a, 0x46, 0xbb, 0xe9, 0xef, 0x59,
	0xdc, 0xdf, 0x26, 0x34, 0xf2, 0xf4, 0x97, 0x11, 0x5f, 0xac, 0xd1, 0x39, 0x54, 0x56, 0x94, 0x04,
	0x34, 0x51, 0xb9, 0x1b, 0x1d, 0xe4, 0xed, 0x79, 0x3f, 0x29, 0x8f, 0x5f, 0x30, 0xd0, 0x2b, 0xb0,
	0x44, 0x16, 0x53, 0x55, 0xef, 0xa8, 0x73, 0xbc, 0xcf, 0xf4, 0x66, 0x59, 0x4c, 0x7d, 0xe5, 0x46,
	0x1e, 0x54, 0x63, 0x92, 0x45, 0x9c, 0x04, 0xaa, 0x7e, 0xa3, 0x73, 0xe2, 0xe5, 0x03, 0xf0, 0xf4,
	0x00, 0xbc, 0x2e, 0xcb, 0x7c, 0x4d, 0x72, 0x7f, 0x18, 0x60, 0xc9, 0x70, 0x54, 0x87, 0xf2, 0x18,
	0xfb, 0x03, 0x6c, 0x3f, 0x42, 0x00, 0x95, 0xe1, 0x60, 0x32, 0xf5, 0xb1, 0x6d, 0xa0, 0x1a, 0x58,
	0xfd, 0x51, 0x77, 0x60, 0x9b, 0xf2, 0x75, 0x35, 0x1d, 0x4e, 0xec, 0x12, 0x6a, 0x42, 0xad, 0x3b,
	0x99, 0x4c, 0x3f, 0x4f, 0x7a, 0xd8, 0xb6, 0x64, 0xe0, 0x08, 0x77, 0x6f, 0xb1, 0x5d, 0x46, 0x0d,
	0xa8, 0x8e, 0xf1, 0xcd, 0x4d, 0x77, 0x80, 0xed, 0x8a, 0xb4, 0xf7, 0x87, 0x23, 0x7c, 0x63, 0x57,
	0xa5, 0xbd, 0x37, 0x1d, 0x8f, 0xf1, 0x64, 0x66, 0xd7, 0x64, 0x9e, 0xd1, 0xf0, 0x1a, 0xdb, 0x75,
	0x55, 0x67, 0x72, 0x3b, 0x9c, 0x61, 0xbb, 0xe3, 0xfe, 0x32, 0xe0, 0xf8, 0x41, 0xf3, 0xc8, 0x03,
	0x2b, 0x20, 0x82, 0x16, 0xe3, 0x39, 0x7b, 0xd0, 0xca, 0x4c, 0xef, 0xd2, 0x57, 0x3c, 0xe4, 0xc8,
	0xee, 0x13, 0xca, 0x44, 0xea, 0x98, 0xad, 0x52, 0xbb, 0xee, 0x6b, 0x28, 0xd7, 0x48, 0xb6, 0x62,
	0xc5, 0x13, 0x35, 0x96, 0xba, 0x5f, 0x20, 0x19, 0x41, 0x82, 0x20, 0xa1, 0x69, 0xea, 0x58, 0xca,
	0xa1, 0xa1, 0xfb, 0xd3, 0x80, 0x66, 0xae, 0x68, 0xc8, 0xee, 0x42, 0x41, 0xd1, 0x11, 0x98, 0xe9,
	0x5a, 0x49, 0x69, 0xfa, 0x66, 0xba, 0x96, 0x17, 0xc0, 0xc8, 0x86, 0xea, 0x0b, 0x90, 0x6f, 0x59,
	0x26, 0x5d, 0xac, 0xe8, 0x86, 0xe8, 0x32, 0x39, 0x42, 0x4f, 0xa1, 0x1e, 0xb2, 0x50, 0x84, 0x44,
	0xf0, 0xa4, 0x28, 0x74, 0x6f, 0x40, 0x2e, 0x54, 0x17, 0x9c, 0x09, 0xb2, 0x10, 0x4e, 0x59, 0x75,
	0x5a, 0xf3, 0x7a, 0x39, 0xf6, 0xb5, 0xc3, 0x7d, 0xbd, 0x53, 0xb3, 0x64, 0x3c, 0xc9, 0xef, 0x92,
	0x24, 0x4b, 0x2a, 0x76, 0x77, 0xa9, 0x90, 0xfb, 0x12, 0x20, 0xe7, 0xf5, 0x23, 0xb2, 0x3c, 0xc8,
	0xba, 0xd2, 0xac, 0x2b, 0x1e, 0x32, 0x39, 0x84, 0x50, 0xf5, 0x98, 0x14, 0x34, 0x0d, 0xf7, 0x95,
	0x99, 0x87, 0x94, 0xbd, 0xd5, 0x7f, 0xa6, 0xcb, 0x18, 0xdf, 0xb2, 0x05, 0xdd, 0x8f, 0x32, 0x0e,
	0x45, 0xbd, 0x80, 0xc7, 0x79, 0xd4, 0x98, 0xa6, 0x29, 0x59, 0x52, 0x39, 0xce, 0x39, 0x0f, 0xb2,
	0x42, 0x81, 0x7a, 0xbb, 0x7f, 0x0c, 0xfd, 0x61, 0xfa, 0x61, 0x44, 0xd3, 0x43, 0xed, 0xec, 0x62,
	0xcd, 0xfb, 0x58, 0x74, 0x0e, 0xd6, 0x9a, 0x66, 0xa9, 0x53, 0x6a, 0x95, 0xda, 0x8d, 0xce, 0xa9,
	0xb7, 0x97, 0xc7, 0xbb, 0xa6, 0x59, 0x8a, 0x99, 0x48, 0x32, 0x5f, 0x71, 0xce, 0xde, 0x41, 0x7d,
	0x67, 0x42, 0x36, 0x94, 0xd6, 0x54, 0xeb, 0x90, 0x4f, 0x74, 0x02, 0xe5, 0x3b, 0x12, 0x6d, 0xf5,
	0xaa, 0x73, 0xf0, 0xc1, 0x7c, 0x6f, 0xb8, 0x1f, 0x75, 0x17, 0x3d, 0xbe, 0xd9, 0x50, 0x26, 0xfe,
	0x47, 0xe1, 0xfd, 0xaa, 0x46, 0xe1, 0xfa, 0xe0, 0x42, 0x2f, 0xad, 0x2f, 0x66, 0x3c, 0x9f, 0x57,
	0xd4, 0xcd, 0xbf, 0xf9, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x2f, 0x9a, 0x38, 0x55, 0xf8, 0x04, 0x00,
	0x00,
}
