// Code generated by protoc-gen-go. DO NOT EDIT.
// source: view.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Directory struct {
	Files                map[string]*File `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Directory) Reset()         { *m = Directory{} }
func (m *Directory) String() string { return proto.CompactTextString(m) }
func (*Directory) ProtoMessage()    {}
func (*Directory) Descriptor() ([]byte, []int) {
	return fileDescriptor_view_5419c27765a82837, []int{0}
}
func (m *Directory) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Directory.Unmarshal(m, b)
}
func (m *Directory) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Directory.Marshal(b, m, deterministic)
}
func (dst *Directory) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Directory.Merge(dst, src)
}
func (m *Directory) XXX_Size() int {
	return xxx_messageInfo_Directory.Size(m)
}
func (m *Directory) XXX_DiscardUnknown() {
	xxx_messageInfo_Directory.DiscardUnknown(m)
}

var xxx_messageInfo_Directory proto.InternalMessageInfo

func (m *Directory) GetFiles() map[string]*File {
	if m != nil {
		return m.Files
	}
	return nil
}

type MobilePreparedFiles struct {
	Dir                  *Directory        `protobuf:"bytes,1,opt,name=dir,proto3" json:"dir,omitempty"`
	Pin                  map[string]string `protobuf:"bytes,2,rep,name=pin,proto3" json:"pin,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *MobilePreparedFiles) Reset()         { *m = MobilePreparedFiles{} }
func (m *MobilePreparedFiles) String() string { return proto.CompactTextString(m) }
func (*MobilePreparedFiles) ProtoMessage()    {}
func (*MobilePreparedFiles) Descriptor() ([]byte, []int) {
	return fileDescriptor_view_5419c27765a82837, []int{1}
}
func (m *MobilePreparedFiles) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MobilePreparedFiles.Unmarshal(m, b)
}
func (m *MobilePreparedFiles) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MobilePreparedFiles.Marshal(b, m, deterministic)
}
func (dst *MobilePreparedFiles) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MobilePreparedFiles.Merge(dst, src)
}
func (m *MobilePreparedFiles) XXX_Size() int {
	return xxx_messageInfo_MobilePreparedFiles.Size(m)
}
func (m *MobilePreparedFiles) XXX_DiscardUnknown() {
	xxx_messageInfo_MobilePreparedFiles.DiscardUnknown(m)
}

var xxx_messageInfo_MobilePreparedFiles proto.InternalMessageInfo

func (m *MobilePreparedFiles) GetDir() *Directory {
	if m != nil {
		return m.Dir
	}
	return nil
}

func (m *MobilePreparedFiles) GetPin() map[string]string {
	if m != nil {
		return m.Pin
	}
	return nil
}

func init() {
	proto.RegisterType((*Directory)(nil), "Directory")
	proto.RegisterMapType((map[string]*File)(nil), "Directory.FilesEntry")
	proto.RegisterType((*MobilePreparedFiles)(nil), "MobilePreparedFiles")
	proto.RegisterMapType((map[string]string)(nil), "MobilePreparedFiles.PinEntry")
}

func init() { proto.RegisterFile("view.proto", fileDescriptor_view_5419c27765a82837) }

var fileDescriptor_view_5419c27765a82837 = []byte{
	// 226 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x41, 0x4b, 0x04, 0x21,
	0x1c, 0x47, 0x51, 0x9b, 0x68, 0xfe, 0x5e, 0xc2, 0x0a, 0x64, 0x2a, 0x18, 0xf6, 0x34, 0x10, 0x18,
	0x4c, 0x10, 0xd1, 0x25, 0x88, 0xea, 0x16, 0x2c, 0x1e, 0xbb, 0xed, 0x34, 0xff, 0x40, 0xb2, 0x51,
	0x6c, 0xda, 0xf0, 0xbb, 0xf4, 0x61, 0x43, 0xa5, 0x76, 0x0f, 0x7b, 0xd3, 0xe7, 0x8f, 0xc7, 0x43,
	0x80, 0xb5, 0xc1, 0x6f, 0xe5, 0x83, 0x9b, 0x5d, 0xc3, 0x3f, 0xdc, 0x88, 0xb6, 0x5c, 0x16, 0x11,
	0xea, 0x07, 0x13, 0xf0, 0x75, 0x76, 0x21, 0x8a, 0x0b, 0xa8, 0xde, 0x8c, 0xc5, 0x4f, 0x49, 0x5a,
	0xd6, 0xf1, 0xfe, 0x44, 0xfd, 0x3f, 0xa9, 0xa7, 0xc4, 0x1f, 0xa7, 0x39, 0x44, 0x5d, 0x36, 0xcd,
	0x1d, 0xc0, 0x06, 0x8a, 0x43, 0x60, 0xef, 0x18, 0x25, 0x69, 0x49, 0x57, 0xeb, 0x74, 0x14, 0xa7,
	0x50, 0xad, 0x57, 0xf6, 0x0b, 0x25, 0x6d, 0x49, 0xc7, 0xfb, 0x2a, 0x2b, 0x74, 0x61, 0xb7, 0xf4,
	0x86, 0x2c, 0x7e, 0x08, 0x1c, 0x3d, 0xbb, 0xc1, 0x58, 0x5c, 0x06, 0xf4, 0xab, 0x80, 0x63, 0xf6,
	0x89, 0x33, 0x60, 0xa3, 0x09, 0x59, 0xc5, 0x7b, 0xd8, 0x34, 0xe8, 0x84, 0xc5, 0x25, 0x30, 0x6f,
	0x26, 0x49, 0x73, 0xe1, 0xb9, 0xda, 0x21, 0x50, 0x4b, 0x33, 0x95, 0xd2, 0xb4, 0x6c, 0xae, 0xe1,
	0xe0, 0x0f, 0xec, 0xa8, 0x3c, 0xde, 0xae, 0xac, 0xb7, 0xf2, 0xee, 0xf7, 0x5e, 0xa8, 0x1f, 0x86,
	0xfd, 0xfc, 0x4d, 0x57, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x7c, 0x85, 0x7d, 0xef, 0x41, 0x01,
	0x00, 0x00,
}
