// Code generated by protoc-gen-go. DO NOT EDIT.
// source: view.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import any "github.com/golang/protobuf/ptypes/any"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type FeedType int32

const (
	FeedType_FLAT      FeedType = 0
	FeedType_ANNOTATED FeedType = 1
	FeedType_HYBRID    FeedType = 2
)

var FeedType_name = map[int32]string{
	0: "FLAT",
	1: "ANNOTATED",
	2: "HYBRID",
}
var FeedType_value = map[string]int32{
	"FLAT":      0,
	"ANNOTATED": 1,
	"HYBRID":    2,
}

func (x FeedType) String() string {
	return proto.EnumName(FeedType_name, int32(x))
}
func (FeedType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_view_b4007d1aebdc4b1f, []int{0}
}

type Directory struct {
	Files                map[string]*File `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Directory) Reset()         { *m = Directory{} }
func (m *Directory) String() string { return proto.CompactTextString(m) }
func (*Directory) ProtoMessage()    {}
func (*Directory) Descriptor() ([]byte, []int) {
	return fileDescriptor_view_b4007d1aebdc4b1f, []int{0}
}
func (m *Directory) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Directory.Unmarshal(m, b)
}
func (m *Directory) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Directory.Marshal(b, m, deterministic)
}
func (dst *Directory) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Directory.Merge(dst, src)
}
func (m *Directory) XXX_Size() int {
	return xxx_messageInfo_Directory.Size(m)
}
func (m *Directory) XXX_DiscardUnknown() {
	xxx_messageInfo_Directory.DiscardUnknown(m)
}

var xxx_messageInfo_Directory proto.InternalMessageInfo

func (m *Directory) GetFiles() map[string]*File {
	if m != nil {
		return m.Files
	}
	return nil
}

type FeedItem struct {
	Block                string   `protobuf:"bytes,1,opt,name=block,proto3" json:"block,omitempty"`
	Body                 *any.Any `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FeedItem) Reset()         { *m = FeedItem{} }
func (m *FeedItem) String() string { return proto.CompactTextString(m) }
func (*FeedItem) ProtoMessage()    {}
func (*FeedItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_view_b4007d1aebdc4b1f, []int{1}
}
func (m *FeedItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FeedItem.Unmarshal(m, b)
}
func (m *FeedItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FeedItem.Marshal(b, m, deterministic)
}
func (dst *FeedItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeedItem.Merge(dst, src)
}
func (m *FeedItem) XXX_Size() int {
	return xxx_messageInfo_FeedItem.Size(m)
}
func (m *FeedItem) XXX_DiscardUnknown() {
	xxx_messageInfo_FeedItem.DiscardUnknown(m)
}

var xxx_messageInfo_FeedItem proto.InternalMessageInfo

func (m *FeedItem) GetBlock() string {
	if m != nil {
		return m.Block
	}
	return ""
}

func (m *FeedItem) GetBody() *any.Any {
	if m != nil {
		return m.Body
	}
	return nil
}

type FeedItemList struct {
	Items                []*FeedItem `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *FeedItemList) Reset()         { *m = FeedItemList{} }
func (m *FeedItemList) String() string { return proto.CompactTextString(m) }
func (*FeedItemList) ProtoMessage()    {}
func (*FeedItemList) Descriptor() ([]byte, []int) {
	return fileDescriptor_view_b4007d1aebdc4b1f, []int{2}
}
func (m *FeedItemList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FeedItemList.Unmarshal(m, b)
}
func (m *FeedItemList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FeedItemList.Marshal(b, m, deterministic)
}
func (dst *FeedItemList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeedItemList.Merge(dst, src)
}
func (m *FeedItemList) XXX_Size() int {
	return xxx_messageInfo_FeedItemList.Size(m)
}
func (m *FeedItemList) XXX_DiscardUnknown() {
	xxx_messageInfo_FeedItemList.DiscardUnknown(m)
}

var xxx_messageInfo_FeedItemList proto.InternalMessageInfo

func (m *FeedItemList) GetItems() []*FeedItem {
	if m != nil {
		return m.Items
	}
	return nil
}

type FeedJoin struct {
	Block                string               `protobuf:"bytes,1,opt,name=block,proto3" json:"block,omitempty"`
	Date                 *timestamp.Timestamp `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	Author               string               `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	Username             string               `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	Avatar               string               `protobuf:"bytes,5,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Likes                []*FeedLike          `protobuf:"bytes,6,rep,name=likes,proto3" json:"likes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *FeedJoin) Reset()         { *m = FeedJoin{} }
func (m *FeedJoin) String() string { return proto.CompactTextString(m) }
func (*FeedJoin) ProtoMessage()    {}
func (*FeedJoin) Descriptor() ([]byte, []int) {
	return fileDescriptor_view_b4007d1aebdc4b1f, []int{3}
}
func (m *FeedJoin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FeedJoin.Unmarshal(m, b)
}
func (m *FeedJoin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FeedJoin.Marshal(b, m, deterministic)
}
func (dst *FeedJoin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeedJoin.Merge(dst, src)
}
func (m *FeedJoin) XXX_Size() int {
	return xxx_messageInfo_FeedJoin.Size(m)
}
func (m *FeedJoin) XXX_DiscardUnknown() {
	xxx_messageInfo_FeedJoin.DiscardUnknown(m)
}

var xxx_messageInfo_FeedJoin proto.InternalMessageInfo

func (m *FeedJoin) GetBlock() string {
	if m != nil {
		return m.Block
	}
	return ""
}

func (m *FeedJoin) GetDate() *timestamp.Timestamp {
	if m != nil {
		return m.Date
	}
	return nil
}

func (m *FeedJoin) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *FeedJoin) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *FeedJoin) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *FeedJoin) GetLikes() []*FeedLike {
	if m != nil {
		return m.Likes
	}
	return nil
}

type FeedJoinList struct {
	Items                []*FeedJoin `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *FeedJoinList) Reset()         { *m = FeedJoinList{} }
func (m *FeedJoinList) String() string { return proto.CompactTextString(m) }
func (*FeedJoinList) ProtoMessage()    {}
func (*FeedJoinList) Descriptor() ([]byte, []int) {
	return fileDescriptor_view_b4007d1aebdc4b1f, []int{4}
}
func (m *FeedJoinList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FeedJoinList.Unmarshal(m, b)
}
func (m *FeedJoinList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FeedJoinList.Marshal(b, m, deterministic)
}
func (dst *FeedJoinList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeedJoinList.Merge(dst, src)
}
func (m *FeedJoinList) XXX_Size() int {
	return xxx_messageInfo_FeedJoinList.Size(m)
}
func (m *FeedJoinList) XXX_DiscardUnknown() {
	xxx_messageInfo_FeedJoinList.DiscardUnknown(m)
}

var xxx_messageInfo_FeedJoinList proto.InternalMessageInfo

func (m *FeedJoinList) GetItems() []*FeedJoin {
	if m != nil {
		return m.Items
	}
	return nil
}

type FeedLeave struct {
	Block                string               `protobuf:"bytes,1,opt,name=block,proto3" json:"block,omitempty"`
	Date                 *timestamp.Timestamp `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	Author               string               `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	Username             string               `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	Avatar               string               `protobuf:"bytes,5,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Likes                []*FeedLike          `protobuf:"bytes,6,rep,name=likes,proto3" json:"likes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *FeedLeave) Reset()         { *m = FeedLeave{} }
func (m *FeedLeave) String() string { return proto.CompactTextString(m) }
func (*FeedLeave) ProtoMessage()    {}
func (*FeedLeave) Descriptor() ([]byte, []int) {
	return fileDescriptor_view_b4007d1aebdc4b1f, []int{5}
}
func (m *FeedLeave) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FeedLeave.Unmarshal(m, b)
}
func (m *FeedLeave) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FeedLeave.Marshal(b, m, deterministic)
}
func (dst *FeedLeave) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeedLeave.Merge(dst, src)
}
func (m *FeedLeave) XXX_Size() int {
	return xxx_messageInfo_FeedLeave.Size(m)
}
func (m *FeedLeave) XXX_DiscardUnknown() {
	xxx_messageInfo_FeedLeave.DiscardUnknown(m)
}

var xxx_messageInfo_FeedLeave proto.InternalMessageInfo

func (m *FeedLeave) GetBlock() string {
	if m != nil {
		return m.Block
	}
	return ""
}

func (m *FeedLeave) GetDate() *timestamp.Timestamp {
	if m != nil {
		return m.Date
	}
	return nil
}

func (m *FeedLeave) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *FeedLeave) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *FeedLeave) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *FeedLeave) GetLikes() []*FeedLike {
	if m != nil {
		return m.Likes
	}
	return nil
}

type FeedLeaveList struct {
	Items                []*FeedLeave `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *FeedLeaveList) Reset()         { *m = FeedLeaveList{} }
func (m *FeedLeaveList) String() string { return proto.CompactTextString(m) }
func (*FeedLeaveList) ProtoMessage()    {}
func (*FeedLeaveList) Descriptor() ([]byte, []int) {
	return fileDescriptor_view_b4007d1aebdc4b1f, []int{6}
}
func (m *FeedLeaveList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FeedLeaveList.Unmarshal(m, b)
}
func (m *FeedLeaveList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FeedLeaveList.Marshal(b, m, deterministic)
}
func (dst *FeedLeaveList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeedLeaveList.Merge(dst, src)
}
func (m *FeedLeaveList) XXX_Size() int {
	return xxx_messageInfo_FeedLeaveList.Size(m)
}
func (m *FeedLeaveList) XXX_DiscardUnknown() {
	xxx_messageInfo_FeedLeaveList.DiscardUnknown(m)
}

var xxx_messageInfo_FeedLeaveList proto.InternalMessageInfo

func (m *FeedLeaveList) GetItems() []*FeedLeave {
	if m != nil {
		return m.Items
	}
	return nil
}

type FeedFiles struct {
	Block                string               `protobuf:"bytes,1,opt,name=block,proto3" json:"block,omitempty"`
	Target               string               `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	Date                 *timestamp.Timestamp `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"`
	Author               string               `protobuf:"bytes,4,opt,name=author,proto3" json:"author,omitempty"`
	Username             string               `protobuf:"bytes,5,opt,name=username,proto3" json:"username,omitempty"`
	Avatar               string               `protobuf:"bytes,6,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Caption              string               `protobuf:"bytes,7,opt,name=caption,proto3" json:"caption,omitempty"`
	Files                []*FeedFile          `protobuf:"bytes,8,rep,name=files,proto3" json:"files,omitempty"`
	Comments             []*FeedComment       `protobuf:"bytes,9,rep,name=comments,proto3" json:"comments,omitempty"`
	Likes                []*FeedLike          `protobuf:"bytes,10,rep,name=likes,proto3" json:"likes,omitempty"`
	Threads              []string             `protobuf:"bytes,11,rep,name=threads,proto3" json:"threads,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *FeedFiles) Reset()         { *m = FeedFiles{} }
func (m *FeedFiles) String() string { return proto.CompactTextString(m) }
func (*FeedFiles) ProtoMessage()    {}
func (*FeedFiles) Descriptor() ([]byte, []int) {
	return fileDescriptor_view_b4007d1aebdc4b1f, []int{7}
}
func (m *FeedFiles) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FeedFiles.Unmarshal(m, b)
}
func (m *FeedFiles) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FeedFiles.Marshal(b, m, deterministic)
}
func (dst *FeedFiles) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeedFiles.Merge(dst, src)
}
func (m *FeedFiles) XXX_Size() int {
	return xxx_messageInfo_FeedFiles.Size(m)
}
func (m *FeedFiles) XXX_DiscardUnknown() {
	xxx_messageInfo_FeedFiles.DiscardUnknown(m)
}

var xxx_messageInfo_FeedFiles proto.InternalMessageInfo

func (m *FeedFiles) GetBlock() string {
	if m != nil {
		return m.Block
	}
	return ""
}

func (m *FeedFiles) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

func (m *FeedFiles) GetDate() *timestamp.Timestamp {
	if m != nil {
		return m.Date
	}
	return nil
}

func (m *FeedFiles) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *FeedFiles) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *FeedFiles) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *FeedFiles) GetCaption() string {
	if m != nil {
		return m.Caption
	}
	return ""
}

func (m *FeedFiles) GetFiles() []*FeedFile {
	if m != nil {
		return m.Files
	}
	return nil
}

func (m *FeedFiles) GetComments() []*FeedComment {
	if m != nil {
		return m.Comments
	}
	return nil
}

func (m *FeedFiles) GetLikes() []*FeedLike {
	if m != nil {
		return m.Likes
	}
	return nil
}

func (m *FeedFiles) GetThreads() []string {
	if m != nil {
		return m.Threads
	}
	return nil
}

type FeedFilesList struct {
	Items                []*FeedFiles `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *FeedFilesList) Reset()         { *m = FeedFilesList{} }
func (m *FeedFilesList) String() string { return proto.CompactTextString(m) }
func (*FeedFilesList) ProtoMessage()    {}
func (*FeedFilesList) Descriptor() ([]byte, []int) {
	return fileDescriptor_view_b4007d1aebdc4b1f, []int{8}
}
func (m *FeedFilesList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FeedFilesList.Unmarshal(m, b)
}
func (m *FeedFilesList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FeedFilesList.Marshal(b, m, deterministic)
}
func (dst *FeedFilesList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeedFilesList.Merge(dst, src)
}
func (m *FeedFilesList) XXX_Size() int {
	return xxx_messageInfo_FeedFilesList.Size(m)
}
func (m *FeedFilesList) XXX_DiscardUnknown() {
	xxx_messageInfo_FeedFilesList.DiscardUnknown(m)
}

var xxx_messageInfo_FeedFilesList proto.InternalMessageInfo

func (m *FeedFilesList) GetItems() []*FeedFiles {
	if m != nil {
		return m.Items
	}
	return nil
}

type FeedFile struct {
	Index                int32      `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	File                 *File      `protobuf:"bytes,2,opt,name=file,proto3" json:"file,omitempty"`
	Links                *Directory `protobuf:"bytes,3,opt,name=links,proto3" json:"links,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *FeedFile) Reset()         { *m = FeedFile{} }
func (m *FeedFile) String() string { return proto.CompactTextString(m) }
func (*FeedFile) ProtoMessage()    {}
func (*FeedFile) Descriptor() ([]byte, []int) {
	return fileDescriptor_view_b4007d1aebdc4b1f, []int{9}
}
func (m *FeedFile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FeedFile.Unmarshal(m, b)
}
func (m *FeedFile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FeedFile.Marshal(b, m, deterministic)
}
func (dst *FeedFile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeedFile.Merge(dst, src)
}
func (m *FeedFile) XXX_Size() int {
	return xxx_messageInfo_FeedFile.Size(m)
}
func (m *FeedFile) XXX_DiscardUnknown() {
	xxx_messageInfo_FeedFile.DiscardUnknown(m)
}

var xxx_messageInfo_FeedFile proto.InternalMessageInfo

func (m *FeedFile) GetIndex() int32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *FeedFile) GetFile() *File {
	if m != nil {
		return m.File
	}
	return nil
}

func (m *FeedFile) GetLinks() *Directory {
	if m != nil {
		return m.Links
	}
	return nil
}

type FeedMessage struct {
	Block                string               `protobuf:"bytes,1,opt,name=block,proto3" json:"block,omitempty"`
	Date                 *timestamp.Timestamp `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	Author               string               `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	Username             string               `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	Avatar               string               `protobuf:"bytes,5,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Body                 string               `protobuf:"bytes,6,opt,name=body,proto3" json:"body,omitempty"`
	Comments             []*FeedComment       `protobuf:"bytes,7,rep,name=comments,proto3" json:"comments,omitempty"`
	Likes                []*FeedLike          `protobuf:"bytes,8,rep,name=likes,proto3" json:"likes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *FeedMessage) Reset()         { *m = FeedMessage{} }
func (m *FeedMessage) String() string { return proto.CompactTextString(m) }
func (*FeedMessage) ProtoMessage()    {}
func (*FeedMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_view_b4007d1aebdc4b1f, []int{10}
}
func (m *FeedMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FeedMessage.Unmarshal(m, b)
}
func (m *FeedMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FeedMessage.Marshal(b, m, deterministic)
}
func (dst *FeedMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeedMessage.Merge(dst, src)
}
func (m *FeedMessage) XXX_Size() int {
	return xxx_messageInfo_FeedMessage.Size(m)
}
func (m *FeedMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_FeedMessage.DiscardUnknown(m)
}

var xxx_messageInfo_FeedMessage proto.InternalMessageInfo

func (m *FeedMessage) GetBlock() string {
	if m != nil {
		return m.Block
	}
	return ""
}

func (m *FeedMessage) GetDate() *timestamp.Timestamp {
	if m != nil {
		return m.Date
	}
	return nil
}

func (m *FeedMessage) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *FeedMessage) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *FeedMessage) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *FeedMessage) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *FeedMessage) GetComments() []*FeedComment {
	if m != nil {
		return m.Comments
	}
	return nil
}

func (m *FeedMessage) GetLikes() []*FeedLike {
	if m != nil {
		return m.Likes
	}
	return nil
}

type FeedMessageList struct {
	Items                []*FeedMessage `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *FeedMessageList) Reset()         { *m = FeedMessageList{} }
func (m *FeedMessageList) String() string { return proto.CompactTextString(m) }
func (*FeedMessageList) ProtoMessage()    {}
func (*FeedMessageList) Descriptor() ([]byte, []int) {
	return fileDescriptor_view_b4007d1aebdc4b1f, []int{11}
}
func (m *FeedMessageList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FeedMessageList.Unmarshal(m, b)
}
func (m *FeedMessageList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FeedMessageList.Marshal(b, m, deterministic)
}
func (dst *FeedMessageList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeedMessageList.Merge(dst, src)
}
func (m *FeedMessageList) XXX_Size() int {
	return xxx_messageInfo_FeedMessageList.Size(m)
}
func (m *FeedMessageList) XXX_DiscardUnknown() {
	xxx_messageInfo_FeedMessageList.DiscardUnknown(m)
}

var xxx_messageInfo_FeedMessageList proto.InternalMessageInfo

func (m *FeedMessageList) GetItems() []*FeedMessage {
	if m != nil {
		return m.Items
	}
	return nil
}

type FeedLike struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Date                 *timestamp.Timestamp `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	Author               string               `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	Username             string               `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	Avatar               string               `protobuf:"bytes,5,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Target               *FeedItem            `protobuf:"bytes,6,opt,name=target,proto3" json:"target,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *FeedLike) Reset()         { *m = FeedLike{} }
func (m *FeedLike) String() string { return proto.CompactTextString(m) }
func (*FeedLike) ProtoMessage()    {}
func (*FeedLike) Descriptor() ([]byte, []int) {
	return fileDescriptor_view_b4007d1aebdc4b1f, []int{12}
}
func (m *FeedLike) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FeedLike.Unmarshal(m, b)
}
func (m *FeedLike) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FeedLike.Marshal(b, m, deterministic)
}
func (dst *FeedLike) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeedLike.Merge(dst, src)
}
func (m *FeedLike) XXX_Size() int {
	return xxx_messageInfo_FeedLike.Size(m)
}
func (m *FeedLike) XXX_DiscardUnknown() {
	xxx_messageInfo_FeedLike.DiscardUnknown(m)
}

var xxx_messageInfo_FeedLike proto.InternalMessageInfo

func (m *FeedLike) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *FeedLike) GetDate() *timestamp.Timestamp {
	if m != nil {
		return m.Date
	}
	return nil
}

func (m *FeedLike) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *FeedLike) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *FeedLike) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *FeedLike) GetTarget() *FeedItem {
	if m != nil {
		return m.Target
	}
	return nil
}

type FeedLikeList struct {
	Items                []*FeedLike `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *FeedLikeList) Reset()         { *m = FeedLikeList{} }
func (m *FeedLikeList) String() string { return proto.CompactTextString(m) }
func (*FeedLikeList) ProtoMessage()    {}
func (*FeedLikeList) Descriptor() ([]byte, []int) {
	return fileDescriptor_view_b4007d1aebdc4b1f, []int{13}
}
func (m *FeedLikeList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FeedLikeList.Unmarshal(m, b)
}
func (m *FeedLikeList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FeedLikeList.Marshal(b, m, deterministic)
}
func (dst *FeedLikeList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeedLikeList.Merge(dst, src)
}
func (m *FeedLikeList) XXX_Size() int {
	return xxx_messageInfo_FeedLikeList.Size(m)
}
func (m *FeedLikeList) XXX_DiscardUnknown() {
	xxx_messageInfo_FeedLikeList.DiscardUnknown(m)
}

var xxx_messageInfo_FeedLikeList proto.InternalMessageInfo

func (m *FeedLikeList) GetItems() []*FeedLike {
	if m != nil {
		return m.Items
	}
	return nil
}

type FeedComment struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Date                 *timestamp.Timestamp `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	Author               string               `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	Username             string               `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	Avatar               string               `protobuf:"bytes,5,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Body                 string               `protobuf:"bytes,6,opt,name=body,proto3" json:"body,omitempty"`
	Target               *FeedItem            `protobuf:"bytes,7,opt,name=target,proto3" json:"target,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *FeedComment) Reset()         { *m = FeedComment{} }
func (m *FeedComment) String() string { return proto.CompactTextString(m) }
func (*FeedComment) ProtoMessage()    {}
func (*FeedComment) Descriptor() ([]byte, []int) {
	return fileDescriptor_view_b4007d1aebdc4b1f, []int{14}
}
func (m *FeedComment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FeedComment.Unmarshal(m, b)
}
func (m *FeedComment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FeedComment.Marshal(b, m, deterministic)
}
func (dst *FeedComment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeedComment.Merge(dst, src)
}
func (m *FeedComment) XXX_Size() int {
	return xxx_messageInfo_FeedComment.Size(m)
}
func (m *FeedComment) XXX_DiscardUnknown() {
	xxx_messageInfo_FeedComment.DiscardUnknown(m)
}

var xxx_messageInfo_FeedComment proto.InternalMessageInfo

func (m *FeedComment) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *FeedComment) GetDate() *timestamp.Timestamp {
	if m != nil {
		return m.Date
	}
	return nil
}

func (m *FeedComment) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *FeedComment) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *FeedComment) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *FeedComment) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *FeedComment) GetTarget() *FeedItem {
	if m != nil {
		return m.Target
	}
	return nil
}

type FeedCommentList struct {
	Items                []*FeedComment `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *FeedCommentList) Reset()         { *m = FeedCommentList{} }
func (m *FeedCommentList) String() string { return proto.CompactTextString(m) }
func (*FeedCommentList) ProtoMessage()    {}
func (*FeedCommentList) Descriptor() ([]byte, []int) {
	return fileDescriptor_view_b4007d1aebdc4b1f, []int{15}
}
func (m *FeedCommentList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FeedCommentList.Unmarshal(m, b)
}
func (m *FeedCommentList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FeedCommentList.Marshal(b, m, deterministic)
}
func (dst *FeedCommentList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeedCommentList.Merge(dst, src)
}
func (m *FeedCommentList) XXX_Size() int {
	return xxx_messageInfo_FeedCommentList.Size(m)
}
func (m *FeedCommentList) XXX_DiscardUnknown() {
	xxx_messageInfo_FeedCommentList.DiscardUnknown(m)
}

var xxx_messageInfo_FeedCommentList proto.InternalMessageInfo

func (m *FeedCommentList) GetItems() []*FeedComment {
	if m != nil {
		return m.Items
	}
	return nil
}

func init() {
	proto.RegisterType((*Directory)(nil), "Directory")
	proto.RegisterMapType((map[string]*File)(nil), "Directory.FilesEntry")
	proto.RegisterType((*FeedItem)(nil), "FeedItem")
	proto.RegisterType((*FeedItemList)(nil), "FeedItemList")
	proto.RegisterType((*FeedJoin)(nil), "FeedJoin")
	proto.RegisterType((*FeedJoinList)(nil), "FeedJoinList")
	proto.RegisterType((*FeedLeave)(nil), "FeedLeave")
	proto.RegisterType((*FeedLeaveList)(nil), "FeedLeaveList")
	proto.RegisterType((*FeedFiles)(nil), "FeedFiles")
	proto.RegisterType((*FeedFilesList)(nil), "FeedFilesList")
	proto.RegisterType((*FeedFile)(nil), "FeedFile")
	proto.RegisterType((*FeedMessage)(nil), "FeedMessage")
	proto.RegisterType((*FeedMessageList)(nil), "FeedMessageList")
	proto.RegisterType((*FeedLike)(nil), "FeedLike")
	proto.RegisterType((*FeedLikeList)(nil), "FeedLikeList")
	proto.RegisterType((*FeedComment)(nil), "FeedComment")
	proto.RegisterType((*FeedCommentList)(nil), "FeedCommentList")
	proto.RegisterEnum("FeedType", FeedType_name, FeedType_value)
}

func init() { proto.RegisterFile("view.proto", fileDescriptor_view_b4007d1aebdc4b1f) }

var fileDescriptor_view_b4007d1aebdc4b1f = []byte{
	// 673 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x54, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0xc5, 0x8e, 0xed, 0xc4, 0x93, 0x16, 0xa2, 0x55, 0xa9, 0xdc, 0x70, 0x68, 0xf0, 0x29, 0x02,
	0xc9, 0x11, 0x45, 0x48, 0x88, 0x0b, 0x4a, 0x69, 0x2b, 0x5a, 0x85, 0x22, 0x59, 0xb9, 0x80, 0xc4,
	0x61, 0x13, 0x6f, 0xd3, 0x55, 0xfc, 0x11, 0xd9, 0x9b, 0x80, 0x7f, 0x1a, 0x07, 0xf8, 0x0d, 0x5c,
	0xf8, 0x3b, 0x08, 0xed, 0x97, 0x93, 0x40, 0x2d, 0xc1, 0x89, 0x72, 0xf3, 0xcc, 0x1b, 0xcf, 0xce,
	0x7b, 0x6f, 0x77, 0x00, 0x56, 0x94, 0x7c, 0x0c, 0x16, 0x79, 0xc6, 0xb2, 0xee, 0xc1, 0x2c, 0xcb,
	0x66, 0x31, 0x19, 0x88, 0x68, 0xb2, 0xbc, 0x1a, 0xe0, 0xb4, 0x54, 0xd0, 0xe1, 0xaf, 0x10, 0xa3,
	0x09, 0x29, 0x18, 0x4e, 0x16, 0xaa, 0xa0, 0x9d, 0x64, 0x11, 0x89, 0x65, 0xe0, 0x97, 0xe0, 0x9e,
	0xd0, 0x9c, 0x4c, 0x59, 0x96, 0x97, 0xe8, 0x31, 0xd8, 0x57, 0x34, 0x26, 0x85, 0x67, 0xf4, 0x1a,
	0xfd, 0xf6, 0xd1, 0xfd, 0xa0, 0x82, 0x82, 0x33, 0x9e, 0x3f, 0x4d, 0x59, 0x5e, 0x86, 0xb2, 0xa6,
	0xfb, 0x12, 0x60, 0x9d, 0x44, 0x1d, 0x68, 0xcc, 0x49, 0xe9, 0x19, 0x3d, 0xa3, 0xef, 0x86, 0xfc,
	0x13, 0x3d, 0x00, 0x7b, 0x85, 0xe3, 0x25, 0xf1, 0xcc, 0x9e, 0xd1, 0x6f, 0x1f, 0xd9, 0xa2, 0x45,
	0x28, 0x73, 0x2f, 0xcc, 0xe7, 0x86, 0x7f, 0x01, 0xad, 0x33, 0x42, 0xa2, 0x73, 0x46, 0x12, 0xb4,
	0x07, 0xf6, 0x24, 0xce, 0xa6, 0x73, 0xd5, 0x40, 0x06, 0xa8, 0x0f, 0xd6, 0x24, 0x8b, 0x4a, 0xd5,
	0x61, 0x2f, 0x90, 0xcc, 0x02, 0xcd, 0x2c, 0x18, 0xa6, 0x65, 0x28, 0x2a, 0xfc, 0x01, 0xec, 0xe8,
	0x5e, 0x23, 0x5a, 0x30, 0x74, 0x08, 0x36, 0x65, 0x24, 0xd1, 0x4c, 0xdc, 0x40, 0xa3, 0xa1, 0xcc,
	0xfb, 0x5f, 0x0c, 0x79, 0xfa, 0x45, 0x46, 0xd3, 0x9a, 0xd3, 0x03, 0xb0, 0x22, 0xcc, 0xf4, 0xfc,
	0xdd, 0xdf, 0x4e, 0x1f, 0x6b, 0x5d, 0x43, 0x51, 0x87, 0xf6, 0xc1, 0xc1, 0x4b, 0x76, 0x9d, 0xe5,
	0x5e, 0x43, 0xb4, 0x51, 0x11, 0xea, 0x42, 0x6b, 0x59, 0x90, 0x3c, 0xc5, 0x09, 0xf1, 0x2c, 0x81,
	0x54, 0xb1, 0xf8, 0x67, 0x85, 0x19, 0xce, 0x3d, 0x5b, 0xfd, 0x23, 0x22, 0x3e, 0x7f, 0x4c, 0xe7,
	0xa4, 0xf0, 0x9c, 0x8d, 0xf9, 0x47, 0x74, 0x4e, 0x42, 0x99, 0xd7, 0x84, 0xf9, 0xf8, 0xf5, 0x84,
	0x39, 0xaa, 0x09, 0x7f, 0x35, 0xc0, 0x15, 0x4d, 0x08, 0x5e, 0x91, 0xff, 0x91, 0xf1, 0x13, 0xd8,
	0xad, 0xe6, 0x17, 0x94, 0x7b, 0xdb, 0x94, 0x21, 0xa8, 0x60, 0xcd, 0xf9, 0xbb, 0x29, 0x39, 0x8b,
	0x7b, 0x5a, 0xc3, 0x79, 0x1f, 0x1c, 0x86, 0xf3, 0x19, 0x61, 0x82, 0xb5, 0x1b, 0xaa, 0xa8, 0xd2,
	0xa2, 0xf1, 0xd7, 0x5a, 0x58, 0xb5, 0x5a, 0xd8, 0xb5, 0x5a, 0x38, 0x5b, 0x5a, 0x78, 0xd0, 0x9c,
	0xe2, 0x05, 0xa3, 0x59, 0xea, 0x35, 0x05, 0xa0, 0x43, 0xae, 0x92, 0x7c, 0xa1, 0xad, 0x0d, 0x95,
	0xe4, 0xc3, 0x12, 0x79, 0xd4, 0x87, 0xd6, 0x34, 0x4b, 0x12, 0x92, 0xb2, 0xc2, 0x73, 0x45, 0xcd,
	0x8e, 0xa8, 0x79, 0x25, 0x93, 0x61, 0x85, 0xae, 0x05, 0x87, 0x9b, 0x05, 0xe7, 0x53, 0xb0, 0xeb,
	0x9c, 0xe0, 0xa8, 0xf0, 0xda, 0xbd, 0x06, 0x9f, 0x42, 0x85, 0xda, 0x0a, 0x21, 0x6b, 0xbd, 0x15,
	0x02, 0xd6, 0x56, 0x7c, 0x90, 0xcf, 0x8d, 0xe7, 0xb8, 0x11, 0x34, 0x8d, 0xc8, 0x27, 0x61, 0x84,
	0x1d, 0xca, 0x00, 0x1d, 0x80, 0xc5, 0x29, 0x6c, 0xaf, 0x0b, 0x91, 0xe2, 0xed, 0x63, 0x9a, 0xce,
	0x0b, 0x65, 0x06, 0xac, 0xf7, 0x52, 0x28, 0x01, 0xff, 0x87, 0x01, 0x6d, 0xde, 0xff, 0x0d, 0x29,
	0x0a, 0x3c, 0xbb, 0x8d, 0xf7, 0x1b, 0xa9, 0x5d, 0x26, 0x9d, 0x16, 0xdf, 0x5b, 0x66, 0x35, 0xff,
	0xcc, 0xac, 0x56, 0xcd, 0xeb, 0x78, 0x06, 0xf7, 0x36, 0xf8, 0x0b, 0x53, 0xfc, 0x6d, 0x53, 0x64,
	0x6b, 0x55, 0xa0, 0x6d, 0xf9, 0xac, 0xd6, 0x20, 0x6f, 0x85, 0xee, 0x82, 0x49, 0x23, 0xa5, 0x98,
	0x49, 0xa3, 0x7f, 0x2a, 0xd7, 0xc3, 0xea, 0x59, 0x3a, 0xe2, 0xf4, 0x8d, 0x0d, 0xae, 0x00, 0xbd,
	0x02, 0xf9, 0xe8, 0xf5, 0x2b, 0x50, 0x6a, 0x24, 0xc9, 0x7e, 0x53, 0x97, 0x44, 0xc9, 0x7b, 0xab,
	0xf8, 0xde, 0x74, 0x3d, 0xd6, 0x1a, 0x34, 0xeb, 0x34, 0x50, 0xb6, 0x2b, 0x46, 0xf5, 0xb6, 0xeb,
	0x1b, 0x25, 0xa1, 0x47, 0x03, 0xe9, 0xfa, 0xb8, 0x5c, 0x10, 0xd4, 0x02, 0xeb, 0x6c, 0x34, 0x1c,
	0x77, 0xee, 0xa0, 0x5d, 0x70, 0x87, 0x97, 0x97, 0x6f, 0xc7, 0xc3, 0xf1, 0xe9, 0x49, 0xc7, 0x40,
	0x00, 0xce, 0xeb, 0x77, 0xc7, 0xe1, 0xf9, 0x49, 0xc7, 0x3c, 0xb6, 0xde, 0x9b, 0x8b, 0xc9, 0xc4,
	0x11, 0x52, 0x3c, 0xfd, 0x19, 0x00, 0x00, 0xff, 0xff, 0xaa, 0x5a, 0x13, 0x83, 0x8a, 0x08, 0x00,
	0x00,
}
